// Original Web Audio score and effects. No copied tracks or cloned voices.
const MELODY=[76,79,81,79,76,72,74,71,72,76,79,76,74,71,69,67,76,79,84,83,81,79,76,74,72,74,76,79,76,74,72,0];
const hz=m=>440*2**((m-69)/12);
export class DiaperAudio {
 constructor(prefs){this.prefs=prefs;this.ctx=null;this.nodes=new Set();this.loops=new Map();this.buffers=new Map();this.nextBeat=0;this.beat=0;this.lastTP=-10;this.lastVoice=-10;this.lastWarning=0;this.lastFoot=0;this.mode='silent';this.currentPower=null;this.ready=false;this.external={};this.externalSource=null;this.duckUntil=0;this.stats={maxVoices:0,notes:0};}
 async unlock(){try{if(!this.ctx){const C=globalThis.AudioContext||globalThis.webkitAudioContext;if(!C)return;this.ctx=new C();const c=this.ctx;this.master=c.createGain();this.master.gain.value=.62;this.compressor=c.createDynamicsCompressor();Object.assign(this.compressor.threshold,{value:-18});this.compressor.knee.value=16;this.compressor.ratio.value=8;this.compressor.attack.value=.004;this.compressor.release.value=.15;this.master.connect(this.compressor).connect(c.destination);this.buses={};for(const id of ['music','ambience','sfx','ui','voice']){const g=c.createGain();g.connect(this.master);this.buses[id]=g;}this.apply();}await this.ctx.resume();this.ready=true;this.nextBeat=this.ctx.currentTime+.03;}catch{}}
 apply(){if(!this.ctx)return;const t=this.ctx.currentTime;for(const [id,g] of Object.entries(this.buses)){const v=this.prefs.mute?0:id==='music'?this.prefs.music:id==='voice'?this.prefs.voice:id==='ambience'?this.prefs.sfx*.25:this.prefs.sfx;g.gain.setTargetAtTime(v,t,.04);}if(this.prefs.mute||this.prefs.voice===0)globalThis.speechSynthesis?.cancel();}
 track(source,gain,duration,when){if(this.nodes.size>=16){source.disconnect();gain.disconnect();return false;}this.nodes.add(source);this.stats.maxVoices=Math.max(this.stats.maxVoices,this.nodes.size);source.onended=()=>{this.nodes.delete(source);source.disconnect();gain.disconnect();};source.start(when);source.stop(when+duration+.025);return true;}
 tone(freq,dur=.13,{bus='sfx',type='triangle',gain=.16,to=freq,at=0}={}){if(!this.ctx||this.ctx.state!=='running'||this.prefs.mute)return;const c=this.ctx,t=Math.max(c.currentTime,at||c.currentTime),o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(15,to),t+dur);g.gain.setValueAtTime(.0001,t);g.gain.linearRampToValueAtTime(gain,t+.006);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g).connect(this.buses[bus]);if(this.track(o,g,dur,t))this.stats.notes++;}
 noiseBuffer(duration=.3){const key=String(duration);if(this.buffers.has(key))return this.buffers.get(key);const b=this.ctx.createBuffer(1,this.ctx.sampleRate*duration,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;this.buffers.set(key,b);return b;}
 noise(dur=.16,{gain=.12,cut=2300,bus='sfx',at=0}={}){if(!this.ctx||this.ctx.state!=='running'||this.prefs.mute)return;const c=this.ctx,t=Math.max(c.currentTime,at||c.currentTime),s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=this.noiseBuffer(.5);f.type='lowpass';f.frequency.value=cut;g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);s.connect(f).connect(g).connect(this.buses[bus]);s.onended=()=>f.disconnect();if(this.track(s,g,dur,t)){const end=s.onended;s.onended=()=>{end?.();f.disconnect();};}}
 voice(text){if(!this.prefs.voice||this.prefs.mute||performance.now()-this.lastVoice<4200)return;this.lastVoice=performance.now();if(text==='¡Afuera!'&&this.external.voiceAfuera&&this.ctx){const s=this.ctx.createBufferSource(),g=this.ctx.createGain();s.buffer=this.external.voiceAfuera;g.gain.value=.6;s.connect(g).connect(this.buses.voice);this.track(s,g,s.buffer.duration,this.ctx.currentTime);return;}if(!globalThis.speechSynthesis)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=this.prefs.language==='en'?'en-US':'es-AR';u.rate=1.2;u.pitch=1.35;u.volume=Math.min(.6,this.prefs.voice);speechSynthesis.speak(u);}
 duck(seconds=.4){if(!this.ctx)return;this.duckUntil=this.ctx.currentTime+seconds;this.buses.music.gain.setTargetAtTime(this.prefs.mute?0:this.prefs.music*.28,this.ctx.currentTime,.025);}
 setMode(mode){if(mode===this.mode)return;this.mode=mode;this.nextBeat=this.ctx?.currentTime||0;this.beat=0;this.stopExternal();if(mode==='running'&&this.external.circus)this.playExternal(this.external.circus,true);if(mode==='over'&&this.external.gameOver)this.playExternal(this.external.gameOver,false);}
 async loadOptional(){try{const manifest=await fetch('./audio/manifest.json').then(r=>r.json());this.manifest=manifest;}catch{this.manifest={};}}
 async decodeOptional(){if(!this.ctx||this.optionalLoaded)return;this.optionalLoaded=true;for(const key of ['circus','gameOver','voiceAfuera','helicopter','chainsaw']){const src=this.manifest?.[key];if(!src)continue;try{const r=await fetch(src);if(r.ok)this.external[key]=await this.ctx.decodeAudioData(await r.arrayBuffer());}catch{}}const mode=this.mode;this.mode='silent';this.setMode(mode);}
 playExternal(buffer,loop){if(!this.ctx)return;const s=this.ctx.createBufferSource();s.buffer=buffer;s.loop=loop;s.connect(this.buses.music);s.start();this.externalSource=s;}
 stopExternal(){if(this.externalSource){try{this.externalSource.stop();}catch{}this.externalSource.disconnect();this.externalSource=null;}}
 startLoop(id){if(!this.ctx||this.loops.has(id)||this.ctx.state!=='running')return;const external=this.external[id==='afuera'?'chainsaw':'helicopter'];if(external){const s=this.ctx.createBufferSource(),g=this.ctx.createGain();s.buffer=external;s.loop=true;g.gain.value=.2;s.connect(g).connect(this.buses.sfx);s.start();this.loops.set(id,{s,g});return;}const c=this.ctx,g=c.createGain(),f=c.createBiquadFilter(),s=c.createBufferSource(),o=c.createOscillator(),mod=c.createOscillator(),mg=c.createGain();s.buffer=this.noiseBuffer(.5);s.loop=true;f.type='lowpass';f.frequency.value=id==='afuera'?1100:420;g.gain.value=id==='afuera'?.065:.1;s.connect(f).connect(g).connect(this.buses.sfx);o.type=id==='afuera'?'sawtooth':'sine';o.frequency.value=id==='afuera'?77:42;o.connect(g);mod.frequency.value=id==='afuera'?26:17;mg.gain.value=.027;mod.connect(mg).connect(g.gain);s.start();o.start();mod.start();this.loops.set(id,{s,o,mod,mg,g,f});}
 stopLoops(){for(const [,l] of this.loops){for(const n of [l.s,l.o,l.mod]){try{n.stop();}catch{}n?.disconnect();}for(const n of [l.mg,l.g,l.f])n?.disconnect();}this.loops.clear();}
 event(e){if(!this.ctx)return;switch(e.type){case'lane':this.noise(.07,{gain:.055,cut:3200});break;case'jump':this.tone(210,.18,{to:850,gain:.09});this.noise(.12,{gain:.06});break;case'slide':this.noise(.27,{gain:.07,cut:1500});break;case'land':case'landing':this.tone(85,.15,{gain:.18,to:35});this.noise(.12,{gain:.06,cut:500});break;case'tp':if(this.ctx.currentTime-this.lastTP>.075){this.lastTP=this.ctx.currentTime;this.noise(.09,{gain:.1,cut:2400});this.tone(650,.12,{gain:.13,to:1200});}break;case'dollar':this.tone(1174,.12,{gain:.13,to:1568});break;case'near':this.duck();this.tone(140,.3,{gain:.17,to:670});break;case'stumble':this.duck();this.tone(175,.2,{type:'square',gain:.12,to:45});this.noise(.2,{gain:.13,cut:650});break;case'power':this.duck(.7);this.tone(392,.24,{gain:.17,to:1046});this.tone(523,.3,{gain:.14,to:1318});if(e.id==='lion'){this.noise(.24,{gain:.15,cut:800});this.tone(180,.28,{type:'sawtooth',to:65,gain:.08});}if(e.id==='afuera'||e.id==='rescue'){this.currentPower=e.id;this.startLoop(e.id);}if(e.id==='afuera')this.voice('¡Afuera!');break;case'powerEnd':this.currentPower=null;this.stopLoops();this.tone(410,.15,{to:200,gain:.06});break;case'destroy':this.noise(.15,{gain:.13,cut:2800});this.tone(100,.1,{gain:.15,to:35});break;case'powerWarning':case'rescueWarning':this.tone(740,.12,{type:'square',gain:.09});break;case'relief':this.duck(.6);for(let i=0;i<4;i++)this.tone([523,659,784,1046][i],.22,{gain:.13,at:this.ctx.currentTime+i*.075});this.voice('¡Salvado!');break;case'fail':this.stopLoops();this.stopExternal();this.mode='silent';this.duck(1);this.tone(140,.2,{gain:.25,type:'square',to:28});this.noise(.17,{gain:.18,cut:700});break;case'end':this.setMode('over');for(let i=0;i<4;i++)this.tone([392,370,349,261][i],.35,{gain:.16,bus:'music',at:this.ctx.currentTime+.15+i*.18});if(e.newRecord)for(let i=0;i<4;i++)this.tone([523,659,784,1046][i],.3,{gain:.14,at:this.ctx.currentTime+1+i*.1});break;case'go':this.tone(523,.15,{gain:.15});this.tone(1046,.28,{gain:.1});break;case'ui':this.tone(720,.07,{bus:'ui',gain:.08,to:460});break;}}
 introCue(shot){if(!this.ctx)return;if(shot===0){for(let i=0;i<3;i++)this.tone([261,329,392][i],.9,{bus:'music',type:'sawtooth',gain:.035});this.noise(.04,{bus:'ambience',gain:.08});}if(shot===1){this.duck(1);this.tone(46,.6,{gain:.16,to:31});this.noise(.3,{gain:.05,cut:150});}if(shot===2){for(let i=0;i<3;i++)this.tone(800,.08,{gain:.07,at:this.ctx.currentTime+i*.17});}if(shot===3){this.noise(.4,{gain:.18,cut:4200});this.setMode('intro');}if(shot===4)this.noise(.3,{gain:.12,cut:3400});}
 tick(engine){const c=this.ctx;if(!c||c.state!=='running')return;const t=c.currentTime;if(this.duckUntil&&t>this.duckUntil){this.duckUntil=0;this.apply();}const running=['RUNNING','TUTORIAL'].includes(engine.state);if(running){this.setMode('running');if(this.currentPower&&!this.loops.has(this.currentPower))this.startLoop(this.currentPower);if(t-this.lastFoot>Math.max(.16,.34-engine.speed*.003)){this.lastFoot=t;this.noise(.045,{gain:.021,cut:500});}if(engine.meter>85&&t>this.lastWarning){const critical=engine.meter>97;this.lastWarning=t+(critical?.28:.75);this.tone(critical?1100:540,.08,{type:'sine',gain:critical?.09:.055});if(engine.meter>93)this.tone(58,.12,{gain:.11,to:38});}}
 if(!['running','intro','over','menu'].includes(this.mode)||this.prefs.music===0||this.prefs.mute)return;if(this.externalSource)return;
 const tempo=this.mode==='over'?70:this.mode==='menu'?104:138,interval=60/tempo/2;if(this.nextBeat<t-.2)this.nextBeat=t+.01;let scheduled=0;while(this.nextBeat<t+.12&&scheduled++<2){const at=this.nextBeat,b=this.beat++,sad=this.mode==='over';this.nextBeat+=interval;const bass=[48,55,48,55,53,60,55,62][Math.floor(b/2)%8];if(b%2===0)this.tone(hz(sad?bass-5:bass),.16,{bus:'music',gain:.105,type:'triangle',at});else{for(const n of [60,64,67])this.tone(hz(n+(Math.floor(b/8)%2?5:0)),.09,{bus:'music',gain:.026,type:'triangle',at});}const note=sad?[72,71,69,67][b%4]:MELODY[b%MELODY.length];if(note)this.tone(hz(note),sad?.3:.15,{bus:'music',gain:sad?.045:.061,type:'triangle',at});if(running&&engine.meter>65&&b%2)this.noise(.035,{bus:'music',gain:.03,cut:5500,at});if(running&&engine.meter>90)this.tone(1800,.028,{bus:'music',gain:.018,at});}}
 pause(){this.stopLoops();this.stopExternal();for(const n of [...this.nodes])try{n.stop();}catch{}globalThis.speechSynthesis?.cancel();this.ctx?.suspend();}
 async resume(engine){await this.unlock();if(engine?.power==='afuera'||engine?.power==='rescue'){this.currentPower=engine.power;this.startLoop(engine.power);}if(this.mode==='running'&&this.external.circus)this.playExternal(this.external.circus,true);}
 dispose(){this.pause();this.ctx?.close();this.ctx=null;}
 snapshot(){return{unlocked:!!this.ctx,state:this.ctx?.state||'none',voices:this.nodes.size,loops:this.loops.size,mode:this.mode,...this.stats};}
}
