// Renderer-free deterministic simulation. All distances are metres; input is in lanes.
export const STATES=Object.freeze({BOOT:'BOOT',MENU:'MENU',INTRO:'INTRO',REPEAT:'REPEAT_INTRO',TUTORIAL:'TUTORIAL',COUNTDOWN:'COUNTDOWN',RUNNING:'RUNNING',PAUSED:'PAUSED',IMPACT:'IMPACT',OVER:'GAME_OVER',RECORD:'NEW_HIGH_SCORE',RESTART:'RESTART_TRANSITION'});
export const POWERS=Object.freeze([
 {id:'magnet',name:'PAPEL MAGNET',duration:8,color:'#51cfff',icon:'🧲'},
 {id:'lion',name:'MODO LEÓN',duration:7,color:'#ffb62e',icon:'🦁'},
 {id:'afuera',name:'¡AFUERA!',duration:6,color:'#ff4e43',icon:'🪚'},
 {id:'dollars',name:'LLUVIA DE DÓLARES',duration:8,color:'#7ff268',icon:'💵'},
 {id:'rescue',name:'RESCATE PRESIDENCIAL',duration:7,color:'#71bdff',icon:'🚁'}
]);
export const QUOTES=Object.freeze(['NO PUEDE SER… ME CAGUÉ ENCIMA.','EL PAPEL HIGIÉNICO ESTABA A 15 METROS…','¿QUÉ VA A DECIR MI MAMÁ?','AL MENOS NADIE ME VIO…','ESTO ES CULPA DE MI HERMANA.','NO HAY PAPEL HIGIÉNICO.','YO QUIERO A MI MAMÁ.','ESTO TAMBIÉN LE PASA A TRUMP.','¿CÓMO ME CAGUÉ SI TENÍA 184 ROLLOS?']);
export const PATTERNS=Object.freeze([
 {name:'single',items:['cone'],lanes:1},
 {name:'low',items:['low'],lanes:1},
 {name:'slide',items:['high'],lanes:1},
 {name:'bus',items:['bus'],lanes:1},
 {name:'construction',items:['block','low'],lanes:2},
 {name:'traffic',items:['bus','cone'],lanes:2},
 {name:'crossing',items:['high','block'],lanes:2},
 {name:'roadwork',items:['gap','low'],lanes:2},
 {name:'moving',items:['vehicle','high'],lanes:2}
]);
const BREAKABLE=new Set(['cone','low','high','block','trash']);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export class ObjectPool {
 constructor(size){this.items=Array.from({length:size},(_,id)=>({id,active:false,kind:'',lane:0,z:0,prevZ:0,y:0,power:'',pull:0,group:0}));this.cursor=0;}
 take(){for(let n=0;n<this.items.length;n++){const o=this.items[this.cursor];this.cursor=(this.cursor+1)%this.items.length;if(!o.active){o.active=true;o.pull=0;o.y=0;o.power='';o.group=0;return o;}}return null;}
 clear(){for(const o of this.items)o.active=false;}
 get count(){let n=0;for(const o of this.items)if(o.active)n++;return n;}
}
export function meterBand(value){return value<=30?0:value<=65?1:value<=85?2:value<=97?3:4;}
export class RunnerEngine {
 constructor({seed=0xDA15,onEvent=()=>{},progress={}}={}){this.seed=seed>>>0;this.onEvent=onEvent;this.pool=new ObjectPool(180);this.progress={bestScore:0,bestDistance:0,bestCombo:0,totalTP:0,runs:0,fullIntro:false,tutorial:false,...progress};this.state=STATES.BOOT;this.previousQuote=-1;this.powerCount=0;this.reset();}
 random(){this.seed=(Math.imul(this.seed,1664525)+1013904223)>>>0;return this.seed/4294967296;}
 emit(type,details={}){this.onEvent({type,...details});}
 reset(){this.pool.clear();this.lane=0;this.x=0;this.jumpTime=0;this.jumpY=0;this.slideTime=0;this.buffer='';this.bufferTime=0;this.distance=0;this.elapsed=0;this.speed=18;this.score=0;this.tp=0;this.dollars=0;this.combo=1;this.bestCombo=1;this.pickupStreak=0;this.meter=20;this.power=null;this.powerTime=0;this.powerWarning=0;this.powerCombo=1;this.powerPayout=0;this.powerGap=13;this.lastPower='';this.nextPattern=4;this.group=0;this.lastSafe=0;this.grace=0;this.slow=0;this.hitStop=0;this.lastActionTime=-10;this.tutorialStep=0;this.tutorialTime=0;this.tutorialSpawned=false;this.tutorialAction=false;this.tutorialCollected=0;this.pendingTutorial=false;this.introTime=0;this.countTime=0;this.restarting=false;this.airY=0;this.landingSafe=0;this.rescueWarning=4;this.wasCritical=false;this.failReason='';this.impactTime=0;this.newRecord=false;this.quote='';this.nearTP=Infinity;this.simTicks=0;}
 menu(){this.endPower();this.pool.clear();this.state=STATES.MENU;this.emit('menu');}
 start({restart=false,tutorial=false}={}){this.endPower();this.reset();this.pendingTutorial=tutorial||!this.progress.tutorial;this.restarting=restart;this.state=restart?STATES.RESTART:this.progress.fullIntro?STATES.REPEAT:STATES.INTRO;this.emit('start',{state:this.state});}
 skipIntro(){if(this.state!==STATES.INTRO&&this.state!==STATES.REPEAT)return;this.progress.fullIntro=true;this.emit('save');this.handoff();}
 handoff(){this.state=this.pendingTutorial?STATES.TUTORIAL:STATES.RUNNING;this.emit('go');if(this.pendingTutorial){this.speed=12;this.emit('tutorial',{step:0});}else this.nextPattern=2.5;}
 pause(){if(![STATES.RUNNING,STATES.TUTORIAL,STATES.INTRO,STATES.REPEAT,STATES.COUNTDOWN,STATES.RESTART].includes(this.state))return;this.resumeState=this.state;this.state=STATES.PAUSED;this.emit('pause');}
 resume(){if(this.state!==STATES.PAUSED)return;if([STATES.RUNNING,STATES.TUTORIAL].includes(this.resumeState)){this.countTarget=this.resumeState;this.countTime=1.5;this.state=STATES.COUNTDOWN;this.emit('resume');}else{this.state=this.resumeState;this.emit('resume');}}
 input(action){if(![STATES.RUNNING,STATES.TUTORIAL].includes(this.state))return false;this.lastActionTime=this.elapsed;
 if(action==='left'||action==='right'){const next=clamp(this.lane+(action==='left'?-1:1),-1,1);if(next===this.lane)return false;this.lane=next;this.emit('lane');if(this.state===STATES.TUTORIAL&&this.tutorialStep===0)this.tutorialAction=true;return true;}
 if(action==='jump'){if(this.airY>.3)return false;if(this.jumpTime>0||this.slideTime>0){this.buffer='jump';this.bufferTime=.16;return false;}this.jumpTime=.84;this.emit('jump');if(this.state===STATES.TUTORIAL&&this.tutorialStep===1)this.tutorialAction=true;return true;}
 if(action==='slide'){if(this.airY>.3)return false;if(this.jumpTime>0){this.buffer='slide';this.bufferTime=.18;return false;}this.slideTime=.8;this.emit('slide');if(this.state===STATES.TUTORIAL&&this.tutorialStep===2)this.tutorialAction=true;return true;}return false;}
 spawn(kind,lane,z=130,y=0,power=''){const o=this.pool.take();if(!o)return null;o.kind=kind;o.lane=lane;o.z=z;o.prevZ=z;o.y=y;o.power=power;o.group=this.group;return o;}
 trail(lane,z,count=4,{dollars=false,arc=false}={}){for(let i=0;i<count;i++)this.spawn(dollars?'dollar':'tp',lane,z+i*3.8,arc?Math.sin(i/(count-1||1)*Math.PI)*1.5:0);}
 pattern(){const band=this.elapsed<30?0:this.elapsed<60?1:this.elapsed<120?2:3;const choice=Math.floor(this.random()*(band===0?(this.elapsed<10?3:4):band===1?6:PATTERNS.length));const pattern=PATTERNS[choice];const safe=clamp(this.lastSafe+(this.random()<.33?-1:this.random()<.5?1:0),-1,1);this.lastSafe=safe;this.group++;const occupied=[-1,0,1].filter(l=>l!==safe);if(this.random()<.5)occupied.reverse();for(let i=0;i<pattern.lanes;i++){const kind=pattern.items[i%pattern.items.length];this.spawn(kind,occupied[i],kind==='vehicle'?188.5:130);if(kind==='low'&&this.random()<.4)this.trail(occupied[i],126,4,{arc:true,dollars:this.power==='dollars'});}
 if(this.random()<.86)this.trail(safe,125,3+Math.floor(this.random()*3),{dollars:this.power==='dollars'});
 // Every group leaves one empty lane; >=1.75s row separation exceeds two lane changes and a jump.
 this.nextPattern=Math.max(1.75,3.05-band*.28-this.elapsed*.0015);if(this.group%6===0)this.nextPattern+=1.6;this.emit('pattern',{name:pattern.name,safe,group:this.group});}
 activate(id){if(!POWERS.some(p=>p.id===id)||this.power)return false;this.power=id;this.powerTime=POWERS.find(p=>p.id===id).duration;this.powerWarning=3;this.powerCombo=1;this.powerPayout=0;this.lastPower=id;this.powerCount++;if(id==='lion'){this.hitStop=.09;this.meter=Math.max(0,this.meter-3);}if(id==='rescue'){this.airY=.05;this.rescueWarning=4;this.jumpTime=this.slideTime=0;for(let j=0;j<4;j++)this.trail((j%3)-1,15+j*23,4);}
 if(id==='dollars')for(let j=0;j<3;j++){this.trail(j-1,25+j*9,4,{dollars:true,arc:j===2});if(j===2)this.spawn('low',1,31);}
 this.emit('power',{id});return true;}
 endPower(){const id=this.power;if(!id)return;this.power=null;this.powerTime=0;if(id==='rescue'){this.landingSafe=3;this.grace=Math.max(this.grace,1);for(const o of this.pool.items)if(o.active&&!['tp','dollar','power'].includes(o.kind)&&o.z<this.speed*3+12)o.active=false;this.emit('landing');}this.emit('powerEnd',{id,payout:this.powerPayout});this.powerPayout=0;}
 pickup(o,relief=5.5){o.active=false;if(o.kind==='tp'){this.tp++;this.pickupStreak++;this.combo=Math.min(12,1+Math.floor(this.pickupStreak/6));this.bestCombo=Math.max(this.bestCombo,this.combo);this.score+=25*this.combo*(this.power==='dollars'?2:1);this.meter=Math.max(0,this.meter-relief);if(this.state===STATES.TUTORIAL)this.tutorialCollected++;this.emit('tp',{lane:o.lane,pulled:o.pull>0});this.checkRelief();}else if(o.kind==='dollar'){const pts=100*this.combo*2;this.dollars++;this.score+=pts;this.powerPayout+=pts;this.emit('dollar',{lane:o.lane});}else if(o.kind==='power'){this.activate(o.power);}}
 checkRelief(){if(this.wasCritical&&this.meter<=65){this.wasCritical=false;this.score+=1000;this.emit('relief',{points:1000});}}
 destroy(o){o.active=false;this.powerCombo=Math.min(5,this.powerCombo+1);this.combo=Math.max(this.combo,this.powerCombo);this.bestCombo=Math.max(this.bestCombo,this.combo);const points=this.power==='afuera'?250:100*this.powerCombo;this.score+=points;this.emit('destroy',{kind:o.kind,lane:o.lane,power:this.power,points});}
 collide(o){o.active=false;if(this.grace>0||this.landingSafe>0)return;if(this.state===STATES.TUTORIAL){this.meter=Math.min(45,this.meter+4);this.grace=1;this.emit('stumble',{kind:o.kind,tutorial:true});return;}if(this.power==='lion'&&BREAKABLE.has(o.kind)){this.destroy(o);return;}if(o.kind==='bus'||o.kind==='vehicle'||o.kind==='gap'){this.fail(o.kind);return;}this.meter=Math.min(100,this.meter+18);this.grace=1.3;this.slow=.65;this.hitStop=.12;this.pickupStreak=0;this.combo=1;this.emit('stumble',{kind:o.kind});if(this.meter>=100)this.fail('meter');}
 fail(reason){if(![STATES.RUNNING,STATES.TUTORIAL].includes(this.state))return;this.failReason=reason;this.state=STATES.IMPACT;this.impactTime=.85;this.hitStop=.16;this.endPower();this.nearTP=Infinity;for(const o of this.pool.items)if(o.active&&o.kind==='tp'&&o.z>0&&Math.abs(o.lane-this.x)<.65)this.nearTP=Math.min(this.nearTP,o.z);this.emit('fail',{reason});}
 finish(){this.newRecord=Math.floor(this.score)>this.progress.bestScore;this.progress.bestScore=Math.max(this.progress.bestScore,Math.floor(this.score));this.progress.bestDistance=Math.max(this.progress.bestDistance,Math.floor(this.distance));this.progress.bestCombo=Math.max(this.progress.bestCombo,this.bestCombo);this.progress.totalTP+=this.tp;this.progress.runs++;let q=this.nearTP<=15&&this.nearTP>=5?1:Math.floor(this.random()*QUOTES.length);if(q===this.previousQuote)q=(q+1)%QUOTES.length;this.previousQuote=q;this.quote=q===8?QUOTES[q].replace('184',String(this.tp)):QUOTES[q];this.state=this.newRecord?STATES.RECORD:STATES.OVER;this.emit('save');this.emit('end',{newRecord:this.newRecord});}
 tutorial(dt){this.tutorialTime+=dt;if(!this.tutorialSpawned){this.tutorialSpawned=true;this.tutorialCollected=0;this.tutorialAction=false;const z=this.speed*1.8;if(this.tutorialStep===0)this.trail(this.lane===1?0:1,12,5);if(this.tutorialStep===1){this.spawn('low',this.lane,z);this.trail(this.lane,z-4,4,{arc:true});}if(this.tutorialStep===2)this.spawn('high',this.lane,z);if(this.tutorialStep===3){this.meter=60;this.trail(this.lane,12,5);}this.emit('tutorial',{step:this.tutorialStep});}
 const success=this.tutorialStep<3?this.tutorialAction:this.tutorialStep===3?this.tutorialCollected>=2:false;
 if((success&&this.tutorialTime>1.6)||(this.tutorialTime>2.4)){this.tutorialStep++;this.tutorialTime=0;this.tutorialSpawned=false;if(this.tutorialStep>=5){this.progress.tutorial=true;this.state=STATES.RUNNING;this.emit('save');this.emit('tutorialDone');this.nextPattern=3;}}}
 update(dt){dt=clamp(dt,0,.05);if(this.state===STATES.INTRO||this.state===STATES.REPEAT){this.introTime+=dt;if(this.introTime>=10){this.progress.fullIntro=true;this.emit('save');this.handoff();}return;}if(this.state===STATES.RESTART){this.introTime+=dt;if(this.introTime>=.35)this.handoff();return;}if(this.state===STATES.COUNTDOWN){this.countTime-=dt;if(this.countTime<=0){this.state=this.countTarget;this.emit('go',{resumed:true});}return;}if(this.state===STATES.IMPACT){if(this.hitStop>0)this.hitStop=Math.max(0,this.hitStop-dt);else{this.impactTime-=dt;if(this.impactTime<=0)this.finish();}return;}if(![STATES.RUNNING,STATES.TUTORIAL].includes(this.state))return;this.simTicks++;
 if(this.hitStop>0){this.hitStop=Math.max(0,this.hitStop-dt);return;}if(this.slow>0){this.slow-=dt;dt*=.55;}this.elapsed+=dt;this.speed=this.state===STATES.TUTORIAL?12:Math.min(40,18+this.elapsed*.11);this.distance+=this.speed*dt;this.score+=this.speed*dt*(this.power==='dollars'?2:1);this.x+=(this.lane-this.x)*(1-Math.exp(-22*dt));this.grace=Math.max(0,this.grace-dt);this.landingSafe=Math.max(0,this.landingSafe-dt);
 const oldJump=this.jumpTime;this.jumpTime=Math.max(0,this.jumpTime-dt);this.slideTime=Math.max(0,this.slideTime-dt);this.jumpY=this.jumpTime>0?Math.sin((1-this.jumpTime/.84)*Math.PI)*2.25:0;if(oldJump>0&&this.jumpTime===0)this.emit('land');if(this.bufferTime>0){this.bufferTime-=dt;if(this.jumpTime===0&&this.slideTime===0){const a=this.buffer;this.bufferTime=0;this.input(a);}}
 if(this.state===STATES.TUTORIAL)this.tutorial(dt);else{const rate=1.22+this.elapsed*.008;this.meter=Math.min(100,this.meter+rate*dt*(this.power==='lion'?.08:this.power==='rescue'?.4:1));if(this.meter>=97)this.wasCritical=true;if(this.meter>=100){this.fail('meter');return;}this.nextPattern-=dt;if(this.nextPattern<=0)this.pattern();this.powerGap-=dt;if(this.powerGap<=0&&!this.power){const r=this.random();let p=r<.35?'magnet':r<.57?'lion':r<.75?'dollars':r<.9?'afuera':'rescue';if(p===this.lastPower)p=POWERS[(POWERS.findIndex(x=>x.id===p)+1)%5].id;this.spawn('power',this.lastSafe,115,0,p);this.powerGap=23+this.random()*12;this.emit('powerSpawn',{id:p});}}
 if(this.power){this.powerTime=Math.max(0,this.powerTime-dt);if(this.power==='rescue'){const sec=Math.ceil(this.powerTime);if(sec<=3&&sec!==this.rescueWarning){this.rescueWarning=sec;this.emit('rescueWarning',{seconds:sec});}}else if(this.powerTime<=2&&this.powerWarning>0){this.powerWarning=0;this.emit('powerWarning');}if(this.powerTime===0)this.endPower();}
 this.airY+=( (this.power==='rescue'?2.9:0)-this.airY)*Math.min(1,dt*3.8);
 for(const o of this.pool.items){if(!o.active)continue;o.prevZ=o.z;o.z-=this.speed*dt*(o.kind==='vehicle'?1.45:1);
 if(o.kind==='tp'&&this.power==='magnet'&&o.z<28&&o.z>-3){o.pull+=dt;o.lane+=(this.x-o.lane)*Math.min(1,dt*8);o.y+=(this.airY+this.jumpY-o.y)*Math.min(1,dt*7);o.z-=dt*18;if(o.z<2.7){this.pickup(o);continue;}}
 if(this.power==='afuera'&&BREAKABLE.has(o.kind)&&Math.abs(o.lane-this.x)<.55&&o.z<14&&o.z>0){this.destroy(o);continue;}
 const crossed=o.z<=1.7&&o.prevZ>=-1.7;if(crossed){const same=Math.abs(o.lane-this.x)<.48;if(['tp','dollar','power'].includes(o.kind)){if(same&&(o.kind==='power'||Math.abs(o.y-this.jumpY)<1.1||this.power==='rescue'))this.pickup(o);}else{if(this.power==='rescue'||this.airY>.5){}else{const clear=o.kind==='low'?this.jumpY>.8:o.kind==='high'?this.slideTime>0:o.kind==='gap'?this.jumpY>.65:false;if(same&&!clear){this.collide(o);if(this.state===STATES.IMPACT)return;}else if(o.z<=0&&o.prevZ>0&&this.state===STATES.RUNNING&&(same&&clear||Math.abs(o.lane-this.x)<1.4&&this.elapsed-this.lastActionTime<.65)){this.score+=75*this.combo;this.slow=.25;this.emit('near');}}}}
 if(o.z<-5)o.active=false;
 }
 }
 snapshot(){return {state:this.state,lane:this.lane,x:this.x,jumpY:this.jumpY,slideTime:this.slideTime,distance:this.distance,score:this.score,tp:this.tp,meter:this.meter,power:this.power,powerTime:this.powerTime,combo:this.combo,bestCombo:this.bestCombo,tutorialStep:this.tutorialStep,elapsed:this.elapsed,speed:this.speed,airY:this.airY,landingSafe:this.landingSafe,objects:this.pool.count,capacity:this.pool.items.length,progress:{...this.progress},reason:this.failReason,quote:this.quote};}
}
