import {RunnerEngine,STATES,POWERS,meterBand} from './engine.js';
import {RunnerRenderer} from './renderer.js';
import {DiaperAudio} from './audio.js';
import {readSave,writeSave} from './storage.js';
const $=s=>document.querySelector(s),all=s=>document.querySelectorAll(s),game=$('#game');
const saved=readSave(),prefs=saved.prefs,assets={};
const audio=new DiaperAudio(prefs);let renderer,screen='boot',dialogReturn='menu',lastTime=0,raf=0,uiTime=0,introShot=-1,toastTimer=0,shareUrl='',shareBlob=null,shareVersion=0,business='',locationName='',shareLink=location.href,calloutTimer=0,countLast='',lastBand=-1,dead=false,lastHud={},frameSamples=[],loadErrors=[];
const engine=new RunnerEngine({progress:saved.progress,onEvent:onEvent});
const I18N={es:{run:'TAP TO RUN',characters:'PERSONAJES',records:'RÉCORDS',achievements:'LOGROS',donate:'APOYAR',how:'¿CÓMO SE JUEGA?',distance:'DISTANCIA',paused:'PAUSADO',safe:'Tu carrera está a salvo. Por ahora.',resume:'▶ SEGUIR CORRIENDO',restart:'↻ RESTART',settings:'CONFIGURACIÓN',menu:'⌂ MENÚ PRINCIPAL',bestCombo:'MEJOR COMBO',record:'RÉCORD',share:'↗ COMPARTIR',music:'MÚSICA',voice:'VOZ',mute:'SILENCIAR TODO',reduced:'MOVIMIENTO REDUCIDO',haptics:'VIBRACIÓN',language:'IDIOMA',reset:'BORRAR PROGRESO',resetConfirm:'¿Borrar récords, papel y logros de este dispositivo?',confirmReset:'BORRAR',cancel:'CANCELAR',cosmetic:'El mismo caos. Un saco distinto. Cambios cosméticos.',choose:'LISTO',local:'Récords de este dispositivo. Sin cuenta.',beat:'SUPERÁ TU RÉCORD',back:'VOLVER',lanes:'CAMBIÁ DE CARRIL',jump:'SALTÁ',slide:'DESLIZATE',goal:'Juntá 🧻 para bajar el Diaper Meter. Al 100%, todo termina. Los colectivos no perdonan.',practice:'PRACTICÁ EN LA PISTA',saveImage:'GUARDAR IMAGEN ↓'},en:{run:'TAP TO RUN',characters:'CHARACTERS',records:'RECORDS',achievements:'ACHIEVEMENTS',donate:'SUPPORT',how:'HOW TO PLAY',distance:'DISTANCE',paused:'PAUSED',safe:'Your run is safe. For now.',resume:'▶ RESUME RUN',restart:'↻ RESTART',settings:'SETTINGS',menu:'⌂ MAIN MENU',bestCombo:'BEST COMBO',record:'BEST',share:'↗ SHARE',music:'MUSIC',voice:'VOICE',mute:'MUTE ALL',reduced:'REDUCED MOTION',haptics:'VIBRATION',language:'LANGUAGE',reset:'RESET PROGRESS',resetConfirm:'Clear records, paper and achievements from this device?',confirmReset:'CLEAR',cancel:'CANCEL',cosmetic:'Same chaos. Different jacket. Cosmetic changes only.',choose:'READY',local:'Personal records on this device. No account.',beat:'BEAT YOUR BEST',back:'BACK',lanes:'CHANGE LANES',jump:'JUMP',slide:'SLIDE',goal:'Collect 🧻 to lower the Diaper Meter. At 100%, it’s over. Dodge buses, jump low barriers and slide under high ones.',practice:'PRACTICE ON THE ROAD',saveImage:'SAVE IMAGE ↓'}};
function save(){writeSave({progress:engine.progress,prefs});}
function tr(){document.documentElement.lang=prefs.language;for(const el of all('[data-i18n]'))el.textContent=I18N[prefs.language][el.dataset.i18n]||el.textContent;game.classList.toggle('reduced-motion',!prefs.motion);}
function text(id,value){if(lastHud[id]===value)return;lastHud[id]=value;$(id).textContent=value;}
function format(n){return Math.floor(n).toLocaleString(prefs.language==='es'?'es-AR':'en-US');}
function show(name){screen=name;for(const el of all('.screen'))el.hidden=el.id!==name;game.dataset.state=engine.state;const live=['run','cinematic','paused','settings','help'].includes(name)&&![STATES.MENU,STATES.OVER,STATES.RECORD,STATES.BOOT].includes(engine.state);$('#hud').hidden=!live;$('#countdown').hidden=engine.state!==STATES.COUNTDOWN;}
function notify(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2100);}
function callout(message,extra=''){clearTimeout(calloutTimer);const el=$('#callout');el.replaceChildren();el.append(document.createTextNode(message));if(extra){const em=document.createElement('em');em.textContent=extra;el.append(em);}el.classList.remove('punch');void el.offsetWidth;el.classList.add('punch');calloutTimer=setTimeout(()=>el.classList.remove('punch'),1000);}
function haptic(pattern){if(prefs.haptics&&!prefs.mute)navigator.vibrate?.(pattern);}
function records(){const p=engine.progress;$('#total-tp').textContent=format(p.totalTP);$('#menu-best').textContent=format(p.bestDistance)+' m';$('#records-list').replaceChildren();for(const [label,value]of [['SCORE',p.bestScore],['DISTANCIA',format(p.bestDistance)+' m'],['MEJOR COMBO','×'+p.bestCombo],['TOTAL 🧻',p.totalTP],['CARRERAS',p.runs]]){const row=document.createElement('div'),l=document.createElement('span'),b=document.createElement('b');l.textContent=label;b.textContent=typeof value==='number'?format(value):value;row.append(l,b);$('#records-list').append(row);}const achievements=[['🏁','PRIMER ESCAPE','Terminá una carrera',p.runs>=1],['🛣','NO ME ALCANZA','Llegá a 500 m',p.bestDistance>=500],['🧻','PAPELITO','Juntá 50 rollos en total',p.totalTP>=50],['🔥','IMPARABLE','Alcanzá un combo ×6',p.bestCombo>=6],['🚀','LARGO CAMINO','Llegá a 2.000 m',p.bestDistance>=2000],['♛','OTRA VEZ','Terminá 10 carreras',p.runs>=10]];$('#achievement-list').replaceChildren();for(const [icon,title,detail,unlocked]of achievements){const row=document.createElement('div'),a=document.createElement('span'),b=document.createElement('div'),strong=document.createElement('b'),small=document.createElement('small');row.className=unlocked?'unlocked':'';a.textContent=unlocked?icon:'🔒';strong.textContent=title;small.textContent=detail;b.append(strong,small);row.append(a,b);$('#achievement-list').append(row);}}
function settingsUI(){for(const id of ['music','sfx','voice']){$('#'+id).value=prefs[id];$('#'+id+'-output').value=Math.round(prefs[id]*100)+'%';}$('#mute').checked=prefs.mute;$('#reduced').checked=!prefs.motion;$('#haptics').checked=prefs.haptics;$('#language').value=prefs.language;$('#reset-confirm').hidden=true;}
function characters(){if(!renderer)return;$('#character-preview').src=renderer.portrait();$('#character-name').textContent=['EL LEÓN','EL LEÓN · NOCHE','EL LEÓN · LIBERTAD'][prefs.character];for(const b of all('[data-character]')){const i=Number(b.dataset.character),unlocked=engine.progress.totalTP>=[0,50,150][i];b.disabled=!unlocked;b.setAttribute('aria-pressed',prefs.character===i);b.querySelector('small').textContent=unlocked?'✓':[0,50,150][i]+' 🧻';}}
function modal(name){if([STATES.INTRO,STATES.REPEAT,STATES.RESTART].includes(engine.state))return;if([STATES.RUNNING,STATES.COUNTDOWN].includes(engine.state))engine.pause();dialogReturn=screen==='run'?'paused':screen;settingsUI();if(name==='characters')characters();if(name==='leaderboard'||name==='achievements')records();show(name);}
function back(){show(dialogReturn);}
async function run({restart=false,}={}){if(dead)return;await audio.unlock();audio.decodeOptional();await introReady;introShot=-1;lastBand=-1;lastHud={};clearTimeout(calloutTimer);$('#callout').classList.remove('punch');$('#intro-meter').hidden=true;$('#cinematic').style.opacity='1';$('#cinematic').removeAttribute('data-shot');renderer.shake=0;for(const p of renderer.particles)p.active=false;engine.start({restart});$('#cinematic').style.pointerEvents='none';if(restart)show('run');else show('cinematic');$('#world').focus({preventScroll:true});}
function onEvent(e){if(e.type==='save')save();if(e.type==='pause'){audio.pause();show('paused');return;}if(e.type==='resume'){audio.resume(engine);show([STATES.INTRO,STATES.REPEAT].includes(engine.state)?'cinematic':'run');return;}if(e.type==='menu'){audio.stopLoops();audio.stopExternal();audio.setMode('menu');records();show('menu');return;}audio.event(e);renderer?.event(e);
 if(e.type==='go'){audio.setMode('running');show('run');if(engine.state===STATES.RUNNING)callout('¡CORRÉ!');}
 if(e.type==='near'){callout(prefs.language==='es'?'¡POR POCO!':'NEAR MISS!','+'+75*engine.combo);haptic(9);}
 if(e.type==='tp')haptic(5);
 if(e.type==='stumble'){callout(prefs.language==='es'?'¡CUIDADO!':'STUMBLE!','DIAPER METER +18%');haptic(35);}
 if(e.type==='power'){callout(POWERS.find(p=>p.id===e.id).name);haptic([10,25,20]);}
 if(e.type==='destroy')callout(e.power==='afuera'?'¡AFUERA!':'🦁 MODO LEÓN','+'+e.points);
 if(e.type==='powerEnd'&&e.id==='dollars'&&e.payout)callout('💵 +'+format(e.payout));
 if(e.type==='rescueWarning')callout(e.seconds+'…',prefs.language==='es'?'ATERRIZAJE':'LANDING');
 if(e.type==='relief'){callout('¡SALVADO!','+1000');haptic([15,20,15]);}
 if(e.type==='fail'){show('run');haptic([35,30,55]);}
 if(e.type==='end'){records();$('#failure-reason').textContent=engine.failReason==='meter'?'DIAPER METER: 100%':engine.failReason==='bus'||engine.failReason==='vehicle'?'COLECTIVO: 1 · DIGNIDAD: 0':'LA CALLE NO PERDONA';$('#quote').textContent=engine.quote;$('#result-distance').textContent=format(engine.distance)+' m';$('#result-tp').textContent=format(engine.tp);$('#result-combo').textContent='×'+engine.bestCombo;$('#result-score').textContent=format(engine.score);$('#result-best').textContent=format(engine.progress.bestScore);$('#new-record').hidden=!engine.newRecord;show('results');}
}
function updateHUD(){text('#distance',format(engine.distance)+' m');text('#tp',format(engine.tp));text('#dollars',format(engine.dollars));text('#combo','×'+engine.combo*(engine.power==='dollars'?2:1));text('#meter-value',Math.floor(engine.meter)+'%');$('#meter-fill').style.width=engine.meter+'%';const band=meterBand(engine.meter),colors=['#8cf347','#ffdf49','#ff9929','#ff4b3f','#ff3159'];if(band!==lastBand){lastBand=band;game.style.setProperty('--meter-color',colors[band]);$('#meter-fill').style.background='linear-gradient(#fff4a2,'+colors[band]+')';$('#meter-status').textContent=(prefs.language==='es'?['TRANQUI','CUIDADO','URGENTE','NO NO NO','CRÍTICO']:['ALL GOOD','CAREFUL','URGENT','NO NO NO','CRITICAL'])[band];}$('#power-hud').hidden=!engine.power;if(engine.power){const p=POWERS.find(p=>p.id===engine.power);if($('#power-name').textContent!==p.name){$('#power-name').textContent=p.name;$('#power-icon').src='./art/power-'+POWERS.indexOf(p)+'.webp';game.style.setProperty('--power-color',p.color);}text('#power-time','0:'+String(Math.ceil(engine.powerTime)).padStart(2,'0'));$('#power-progress').value=engine.powerTime/p.duration;}}
function intro(){const full=engine.state===STATES.INTRO,t=engine.introTime;let shot=full?t<1.3?0:t<2.1?1:t<3?2:t<4.1?3:t<5.3?4:5:t<.4?1:t<.82?4:5;if(shot!==introShot){introShot=shot;$('#cinematic').dataset.shot=shot;$('#intro-character').src='./art/'+['speech','panic','panic','rage','escape','escape'][shot]+'.webp';$('#intro-meter').hidden=shot!==2;$('#intro-caption').textContent=['DISCURSO PRESIDENCIAL','UN MOMENTO…','¡SE VIENE!','¡AFUERA!','¡CORRÉ!',''][shot];audio.introCue(shot);}if(shot===5){$('#cinematic').style.opacity=String(full?Math.max(0,(6-t)/.7):Math.max(0,(1-t)/.18));$('#hud').hidden=false;}else $('#cinematic').style.opacity='1';}
function resetProgress(){Object.assign(engine.progress,{bestScore:0,bestDistance:0,bestCombo:0,totalTP:0,runs:0,fullIntro:false});prefs.character=0;save();records();$('#reset-confirm').hidden=true;notify(prefs.language==='es'?'Progreso borrado.':'Progress cleared.');}
async function prepareShare(){const version=++shareVersion;dialogReturn='results';show('share');$('#share-note').textContent=prefs.language==='es'?'Preparando tu tarjeta…':'Preparing your card…';$('#share-image').removeAttribute('src');$('#download').removeAttribute('href');try{await document.fonts.ready;const c=document.createElement('canvas');c.width=720;c.height=1280;const g=c.getContext('2d');g.fillStyle='#07172e';g.fillRect(0,0,720,1280);if(assets.results)g.drawImage(assets.results,0,130,720,720);const grad=g.createLinearGradient(0,600,0,1280);grad.addColorStop(0,'#07172e00');grad.addColorStop(.4,'#07172e');g.fillStyle=grad;g.fillRect(0,600,720,680);g.textAlign='center';g.font='58px Diaper';g.fillStyle='#ffe14b';g.strokeStyle='#06203b';g.lineWidth=9;g.strokeText('EL LEÓN SE CAGÓ',360,95);g.fillText('EL LEÓN SE CAGÓ',360,95);g.fillStyle='#fff7e4';g.font='23px Diaper';g.fillText('DIAPER RUN · ¡AFUERA! EDITION',360,140);g.font='90px Diaper';g.fillStyle='#ffe24e';g.fillText(format(engine.distance)+' m',360,850);g.fillStyle='#fff6df';g.font='30px Diaper';g.fillText('🧻 '+engine.tp+'     COMBO ×'+engine.bestCombo,360,915);g.font='24px Diaper';g.fillStyle='#93d4f3';g.fillText('SCORE '+format(engine.score),360,974);if(engine.newRecord){g.font='31px Diaper';g.fillStyle='#ffd948';g.fillText('♛ NUEVO RÉCORD',360,1035);}g.font='20px Diaper';g.fillStyle='#fff4df';const quote=engine.quote;const words=quote.split(' ');let line='',y=1090;for(const w of words){if(g.measureText(line+w).width>630){g.fillText(line,360,y);y+=27;line='';}line+=w+' ';}g.fillText(line,360,y);if(business){g.fillStyle='#8ccbf0';g.font='18px Arial';g.fillText('UGC GAMES · '+[business,locationName].filter(Boolean).join(' · '),360,1196,650);}g.strokeStyle='#62bbec';g.lineWidth=3;g.strokeRect(16,16,688,1248);const blob=await new Promise(resolve=>c.toBlob(resolve,'image/png'));if(!blob)throw Error('No image');if(version!==shareVersion)return;disposeShare();shareBlob=blob;shareUrl=URL.createObjectURL(blob);$('#share-image').src=shareUrl;$('#download').href=shareUrl;$('#share-note').textContent=prefs.language==='es'?'Compartí con tu app favorita o guardá la imagen.':'Share with your favorite app or save the image.';}catch{$('#share-note').textContent='No se pudo crear la tarjeta. Volvé e intentá de nuevo.';}}
function disposeShare(){if(shareUrl)URL.revokeObjectURL(shareUrl);shareUrl='';shareBlob=null;}
async function nativeShare(){if(!shareBlob)return;const file=new File([shareBlob],'diaper-run-result.png',{type:'image/png'});try{if(navigator.canShare?.({files:[file]})&&navigator.share){await navigator.share({files:[file],title:'El León se Cagó — Diaper Run',text:format(engine.distance)+' m · 🧻 '+engine.tp+' · Combo ×'+engine.bestCombo});}else if(navigator.share){await navigator.share({title:'Diaper Run',text:format(engine.distance)+' m · 🧻 '+engine.tp,url:shareLink});}else $('#download').click();}catch(e){if(e.name!=='AbortError'){$('#download').click();$('#share-note').textContent='Guardá la imagen y compartila desde tu app.';}}}
for(const el of all('[data-action]'))el.addEventListener('click',async()=>{audio.unlock();audio.event({type:'ui'});const a=el.dataset.action;if(a==='run')run();else if(a==='restart')run({restart:true});else if(a==='resume')engine.resume();else if(a==='menu'){disposeShare();engine.menu();}else if(a==='exit'){engine.menu();audio.pause();if(parent!==window)parent.postMessage({type:'GAME_EXIT'},location.origin);}else if(['settings','characters','leaderboard','achievements','donate','help'].includes(a))modal(a);else if(a==='back')back();else if(a==='skip-intro')engine.skipIntro();else if(a==='share')prepareShare();else if(a==='native-share')nativeShare();else if(a==='reset')$('#reset-confirm').hidden=false;else if(a==='cancel-reset')$('#reset-confirm').hidden=true;else if(a==='confirm-reset')resetProgress();else if(a==='copy-alias'){try{await navigator.clipboard.writeText('Daiske.mp');$('#donation-note').textContent='Alias copiado. Abrí Mercado Pago y transferí a Daiske.mp.';}catch{$('#donation-note').textContent='Alias: Daiske.mp — copialo en tu app de Mercado Pago.';}}});
for(const id of ['music','sfx','voice'])$('#'+id).addEventListener('input',e=>{prefs[id]=Number(e.target.value);$('#'+id+'-output').value=Math.round(prefs[id]*100)+'%';audio.apply();save();});
for(const id of ['mute','reduced','haptics'])$('#'+id).addEventListener('change',e=>{prefs[id==='reduced'?'motion':id]=id==='reduced'?!e.target.checked:e.target.checked;audio.apply();tr();save();});
$('#language').addEventListener('change',e=>{prefs.language=e.target.value;tr();lastHud={};lastBand=-1;save();});
for(const b of all('[data-character]'))b.addEventListener('click',()=>{prefs.character=Number(b.dataset.character);characters();save();audio.event({type:'ui'});});
for(const b of all('[data-amount]'))b.addEventListener('click',()=>{for(const other of all('[data-amount]'))other.setAttribute('aria-pressed',other===b);$('#other-amount').value=b.dataset.amount;$('#donation-note').textContent='$'+format(Number(b.dataset.amount))+' ARS · Alias Daiske.mp. No se hizo ningún cobro.';});
$('#pause').addEventListener('click',()=>engine.pause());
const keys={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',ArrowUp:'jump',w:'jump',W:'jump',' ':'jump',ArrowDown:'slide',s:'slide',S:'slide'};
function keydown(e){if(/^(INPUT|SELECT|TEXTAREA)$/.test(e.target.tagName))return;if(e.key==='Escape'||e.key==='p'||e.key==='P'){if(engine.state===STATES.PAUSED&&screen==='paused')engine.resume();else engine.pause();e.preventDefault();return;}if(keys[e.key]&&[STATES.RUNNING].includes(engine.state)){e.preventDefault();if(!e.repeat)engine.input(keys[e.key]);}}
window.addEventListener('keydown',keydown);let pointer=null;
$('#world').addEventListener('pointerdown',e=>{if(![STATES.RUNNING].includes(engine.state))return;e.preventDefault();pointer={id:e.pointerId,x:e.clientX,y:e.clientY};$('#world').setPointerCapture(e.pointerId);});
$('#world').addEventListener('pointermove',e=>{if(!pointer||e.pointerId!==pointer.id)return;e.preventDefault();const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y,threshold=Math.max(18,Math.min(30,innerWidth*.055));if(Math.max(Math.abs(dx),Math.abs(dy))<threshold)return;engine.input(Math.abs(dx)>Math.abs(dy)?dx<0?'left':'right':dy<0?'jump':'slide');pointer.x=e.clientX;pointer.y=e.clientY;});
for(const name of ['pointerup','pointercancel','lostpointercapture'])$('#world').addEventListener(name,e=>{if(pointer?.id===e.pointerId)pointer=null;});
function pauseHidden(){pointer=null;engine.pause();audio.pause();}
document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseHidden();});window.addEventListener('blur',()=>{if([STATES.RUNNING,STATES.INTRO,STATES.REPEAT,STATES.COUNTDOWN].includes(engine.state))pauseHidden();});
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.type==='DIAPER_RUN_PAUSE')engine.pause();if(e.data?.type==='MENUTAP_GAME_CONTEXT'){business=String(e.data.businessName||'').slice(0,60);locationName=String(e.data.locationName||'').slice(0,70);shareLink=String(e.data.shareUrl||location.href);$('.brand-pill').textContent=business?business.toUpperCase():'UGC GAMES';}});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>renderer?.resize(),80);});
function loop(t){if(dead)return;const raw=lastTime?(t-lastTime)/1000:0;lastTime=t;const dt=Math.min(.05,raw);const before=engine.state;engine.update(dt);if(before!==engine.state)game.dataset.state=engine.state;
 const active=[STATES.RUNNING,STATES.INTRO,STATES.REPEAT,STATES.COUNTDOWN,STATES.RESTART,STATES.IMPACT].includes(engine.state);if(active)renderer.draw(engine,engine.state===STATES.COUNTDOWN?0:dt);if(engine.state===STATES.INTRO||engine.state===STATES.REPEAT)intro();if(engine.state===STATES.COUNTDOWN){$('#countdown').hidden=false;const label=String(Math.max(1,Math.ceil(engine.countTime/.3)));if(label!==countLast){countLast=label;$('#countdown').textContent=label;audio.event({type:'go'});}}else{$('#countdown').hidden=true;countLast='';}
 uiTime+=dt;if(active&&uiTime>.06){uiTime=0;updateHUD();}audio.tick(engine);if(raw>0&&active){frameSamples.push(raw*1000);if(frameSamples.length>180)frameSamples.shift();}raf=requestAnimationFrame(loop);}
function cleanup(){dead=true;cancelAnimationFrame(raf);clearTimeout(toastTimer);clearTimeout(calloutTimer);clearTimeout(resizeTimer);audio.dispose();disposeShare();}
window.addEventListener('pagehide',e=>{if(e.persisted)pauseHidden();else cleanup();});
window.addEventListener('pageshow',e=>{if(e.persisted){lastTime=0;notify('Pausado. Tocá continuar.');}});
tr();settingsUI();audio.loadOptional();
let loaded=0;async function load(id){try{const i=new Image();i.src='./art/'+id+'.webp';await i.decode();assets[id]=i;}catch(e){loadErrors.push(id);}finally{loaded++;$('#loading').value=loaded/26;}}
const introReady=Promise.all(['stage','speech','realization','panic','rage','escape'].map(load));
const otherReady=Promise.all(['results','donate','power-0','power-1','power-2','power-3','power-4','runner-v2-0','runner-v2-1','runner-v2-2','runner-v2-3','prop-v2-bus','prop-v2-low','prop-v2-high','prop-v2-cone','prop-v2-tp','prop-v2-dollar'].map(load));
try{await Promise.all([load('menu-v2'),load('environment'),load('street-v3'),document.fonts.ready]);renderer=new RunnerRenderer($('#world'),prefs,assets);renderer.draw(engine,0);engine.menu();raf=requestAnimationFrame(loop);parent.postMessage({type:'GAME_READY'},location.origin);
 if(new URLSearchParams(location.search).get('test')==='1')window.DiaperDebug={engine,renderer,audio,prefs,assets,ready:()=>Promise.all([introReady,otherReady]),start:()=>{engine.reset();engine.state=STATES.RUNNING;show('run');},advance:s=>{for(let t=0;t<s;t+=1/60)engine.update(Math.min(1/60,s-t));updateHUD();renderer.draw(engine,0);},input:a=>engine.input(a),activate:id=>engine.activate(id),spawn:(...args)=>engine.spawn(...args),snapshot:()=>({...engine.snapshot(),screen,loadErrors,audio:audio.snapshot(),fps:1000/(frameSamples.reduce((a,b)=>a+b,0)/(frameSamples.length||1))}),save,run,share:prepareShare};
}catch(e){console.error(e);$('#boot p').textContent='No se pudo abrir la pista. Recargá para intentar de nuevo.';}
