// Change this one value to rename the launch page.
const GAME_NAME = 'Diaper Boy Milei';
document.querySelectorAll('[data-game-name]').forEach(el=>el.textContent=GAME_NAME);
document.title=`${GAME_NAME} · Corré.`;
const gallery=document.querySelector('.gallery');
gallery.addEventListener('scroll',()=>{const i=Math.round(gallery.scrollLeft/(gallery.children[0].offsetWidth+12));document.querySelector('#slide-count').textContent=`${String(i+1).padStart(2,'0')} / 06`;document.querySelectorAll('.dots i').forEach((dot,n)=>dot.classList.toggle('active',i===n));},{passive:true});
let data=[],shown=0;
const handles=['peluca_runner','flor.mp','nacho.32','luqui_','mili.jpeg','termas2026','tomi.b','agus.mp','camii','rocio.ok','mate_amargo','facu.v','pablo.arg','sofi.99','el_pibe_del_152','julieta.mp','santi_','vale.27','bruno.zip','maru.mp','gaston.b','el_falcon','cande_','nicolas.mp','fede.ros','lola.arg','fin_de_mes','martin.83','sol.mp','tino.r'];
function loadReviews(){const frag=document.createDocumentFragment();data.slice(shown,shown+10).forEach((r,j)=>{const n=shown+j,el=document.createElement('article');el.className='review';const user=handles[n%handles.length]+(n>=handles.length?'_2':'');const stars=n===8?3:n===10?4:n===12?2:r.stars;el.innerHTML=`<div class="review-head"><span class="avatar" style="--avatar:${['#24485e','#53405e','#3c553b','#634637'][n%4]}">${user.slice(0,2).toUpperCase()}</span><span class="review-user">@${user}</span><span class="review-time">${['hace 2 min','hace 14 min','ayer','hace 3 días','hace 1 h'][n%5]}</span></div><div class="review-stars" aria-label="${stars} de 5 estrellas">${'★'.repeat(stars)}${'☆'.repeat(5-stars)}</div><p></p><div class="review-actions">${n%3?'♡':'👍'} ${[382,'1.2K',47,916,128,63][n%6]} · comentario ficticio</div>`;el.querySelector('p').textContent=r.text;if(n===4||n===16){const reply=document.createElement('div');reply.className='review-reply';reply.textContent=n===4?'@otro_pibe: lo mandaron al grupo de mi laburo 💀':'@mate_amargo: transporte público premium';el.append(reply)}frag.append(el)});shown=Math.min(shown+10,data.length);document.querySelector('#reviews').append(frag);document.querySelector('#more-reviews').textContent=shown<data.length?`VER MÁS RESEÑAS (${shown}/${data.length}) ↓`:'VISTE TODO EL CAOS ✓';document.querySelector('#more-reviews').disabled=shown>=data.length;}
fetch('reviews.json').then(r=>r.json()).then(r=>{data=r;loadReviews()}).catch(()=>document.querySelector('#more-reviews').textContent='No se pudieron cargar las reseñas');
document.querySelector('#more-reviews').addEventListener('click',loadReviews);
const dialog=document.querySelector('#game-dialog'),frame=document.querySelector('#game-frame');let returnFocus;
function closeGame(){dialog.close();frame.removeAttribute('src');document.body.style.overflow='';returnFocus?.focus();}
document.querySelectorAll('.play').forEach(b=>b.addEventListener('click',()=>{returnFocus=b;dialog.showModal();document.body.style.overflow='hidden';document.querySelector('#game-loading').hidden=false;frame.src='game/';}));
document.querySelector('#close-game').addEventListener('click',closeGame);dialog.addEventListener('cancel',e=>{e.preventDefault();closeGame()});
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==frame.contentWindow)return;if(e.data?.type==='GAME_EXIT')closeGame();if(e.data?.type==='GAME_READY'){document.querySelector('#game-loading').hidden=true;frame.contentWindow.postMessage({type:'MENUTAP_GAME_CONTEXT',businessName:GAME_NAME},location.origin)}});
document.querySelector('#share').addEventListener('click',async()=>{const status=document.querySelector('#share-status');const share={title:GAME_NAME,text:'¿Me ganás? Corré por Argentina. La prensa te sigue y el papel se acaba.',url:location.origin+location.pathname};try{if(navigator.share){await navigator.share(share);status.textContent='Desafío compartido.'}else{await navigator.clipboard.writeText(`${share.text} ${share.url}`);status.textContent='Link copiado. Mandalo al grupo.'}}catch(e){if(e.name!=='AbortError')status.textContent='Compartí este enlace: '+share.url}});
let ticker;const live=document.querySelector('.live');const motion=matchMedia('(prefers-reduced-motion: reduce)');new IntersectionObserver(entries=>{const visible=entries[0].isIntersecting;live.querySelectorAll('i,.live-comments span').forEach(el=>el.style.animationPlayState=visible?'running':'paused');clearInterval(ticker);if(visible&&!motion.matches)ticker=setInterval(()=>document.querySelector('#viewers').textContent=(24.8+Math.random()*.2).toFixed(1)+'K',5000)},{threshold:.1}).observe(live);
