const fs=require('node:fs'),assert=require('node:assert/strict');
const pw=require(process.env.PLAYWRIGHT_MODULE||'playwright'),base=process.env.AUDIT_BASE||'http://127.0.0.1:5198';
const checks=[],errors=[],check=(label,value)=>{assert(value,label);checks.push(label);console.log('PASS',label)};
(async()=>{const browser=await pw.chromium.launch({channel:'chrome',headless:true});const p=await browser.newPage({viewport:{width:1024,height:768},hasTouch:true});p.on('pageerror',e=>errors.push(e.stack));
try{
 await p.goto(base+'/game/?test=1&testCharacters=1');await p.waitForFunction(()=>window.DiaperDebug,{},{timeout:60000});await p.addStyleTag({content:'#acceptance-controls,#acceptance-stats{display:none!important}'});
 await p.locator('#menu [data-action=characters]').tap();await p.locator('[data-select-step="1"]').tap();check('selector next arrow advances',await p.locator('#characters').getAttribute('data-runner')==='trump');await p.locator('[data-select-step="-1"]').tap();check('selector previous arrow returns',await p.locator('#characters').getAttribute('data-runner')==='milei');
 check('selector arrows are centered',await p.locator('.selector-arrow').evaluateAll(items=>items.every(e=>{const r=e.getBoundingClientRect(),s=e.querySelector('svg').getBoundingClientRect();return Math.abs(r.x+r.width/2-s.x-s.width/2)<1&&Math.abs(r.y+r.height/2-s.y-s.height/2)<1})));
 await p.locator('#selector-play').tap();await p.waitForFunction(()=>DiaperDebug.engine.state==='INTRO');await p.locator('[data-action=skip-intro]').tap();await p.evaluate(()=>{const e=DiaperDebug.engine;e.pool.clear();e.nextPattern=e.powerGap=999;e.meter=10});
 const cdp=await p.context().newCDPSession(p);
 for(const [action,dx,dy]of[['right',100,0],['left',-100,0],['jump',0,-100],['slide',0,100]]){
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:510,y:350,id:1}]});for(let n=1;n<=5;n++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:510+dx*n/5,y:350+dy*n/5,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  check('native touch swipe '+action,await p.evaluate(a=>DiaperDebug.engine.inputHistory.at(-1).action===a,action));await p.waitForTimeout(action==='jump'?850:200);
 }
 await p.evaluate(()=>DiaperDebug.activate('rescue'));await p.waitForTimeout(1300);await p.setViewportSize({width:768,height:1024});await p.waitForTimeout(250);check('rotate during flight preserves active game',await p.evaluate(()=>DiaperDebug.engine.state==='RUNNING'&&DiaperDebug.engine.power==='rescue'&&Math.abs(DiaperDebug.renderer.camera.aspect-768/1024)<.01));
 await p.evaluate(()=>DiaperDebug.engine.menu());await p.locator('#menu [data-action=leaderboard]').tap();await p.locator('#leaderboard [data-action=run]').tap();await p.waitForFunction(()=>DiaperDebug.engine.state==='INTRO');check('records Play opens selected intro',true);await p.locator('[data-action=skip-intro]').tap();await p.evaluate(()=>{DiaperDebug.engine.fail('meter');DiaperDebug.advance(2)});await p.locator('#results [data-action=share]').tap();await p.waitForFunction(()=>document.querySelector('#share-image').naturalWidth===720);await p.evaluate(()=>{window.cancelShareCalls=0;Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>true});Object.defineProperty(navigator,'share',{configurable:true,value:async()=>{window.cancelShareCalls++;throw new DOMException('cancelled','AbortError')}})});await p.locator('#share [data-action=native-share]').tap();check('native share cancellation keeps game open',await p.evaluate(()=>window.cancelShareCalls===1&&DiaperDebug.snapshot().screen==='share'));
 await p.goto(base);await p.locator('.get-row .play').tap();const frame=p.frameLocator('#game-frame');await frame.locator('#menu').waitFor({timeout:60000});await frame.locator('#menu [data-action=run]').tap();await frame.locator('#cinematic').waitFor();await frame.locator('[data-action=skip-intro]').tap();await p.keyboard.press('Escape');await frame.locator('#paused').waitFor();check('Escape pauses iframe game without closing it',await p.locator('#game-dialog').isVisible());await frame.locator('#paused [data-action=resume]').tap();await frame.locator('#paused').waitFor({state:'hidden'});await p.locator('#close-game').tap();check('close works from active gameplay',!await p.locator('#game-dialog').isVisible());
 check('no input-path runtime errors',!errors.length);
}finally{fs.writeFileSync('/private/tmp/diaper-input-audit.json',JSON.stringify({checks,errors},null,2));await browser.close()}console.log('TOTAL',checks.length,'PASS')})().catch(e=>{console.error(e);process.exit(1)});
