import {BONUS_POWERS} from './characters.js';
import {DiaperAudio as LegacyAudio} from '../audio.js';
export class DiaperAudio extends LegacyAudio{
 async unlock(){const resumed=super.unlock();await resumed;if(this.ctx?.state==='running')void this.decodeOptional();if(this.mode==='menu')this.setMode('menu');}
 setMode(mode){super.setMode(mode);if(mode==='menu'&&this.external.menuComedy&&!this.externalSource)this.playExternal(this.external.menuComedy,true,.35);}
 async fetchOptional(src){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(src,{signal:controller.signal});if(!response.ok)throw Error('Audio unavailable');return await response.arrayBuffer();}finally{clearTimeout(timer);}}
 async loadOptional(){if(!this.manifestReady)this.manifestReady=this.fetchOptional(new URL('../audio/manifest-v3.json',import.meta.url)).then(bytes=>JSON.parse(new TextDecoder().decode(bytes))).catch(()=>({}));this.manifest=await this.manifestReady;return this.manifest;}
 async decodeOptional(){if(!this.ctx)return;if(!this.decodePromise)this.decodePromise=this.decodeSamples();return this.decodePromise;}
 async decodeSamples(){
  if(!this.ctx||this.optionalLoaded)return;this.optionalLoaded=true;await this.loadOptional();this.sampleFX={};this.sampleLoops={};this.audioErrors=[];
  const decode=async src=>{try{const bytes=await this.fetchOptional(new URL('../audio/'+src,import.meta.url));if(!this.ctx||this.disposed)return null;return await this.ctx.decodeAudioData(bytes);}catch{this.audioErrors.push(src);return null;}};
  await Promise.all([
   ...['circus','gameOver','introComedy','menuComedy'].map(async key=>{if(!this.manifest[key])return;const buffer=await decode(this.manifest[key]);if(!buffer||this.disposed)return;this.external[key]=buffer;const active={menu:'menuComedy',running:'circus',intro:'introComedy',over:'gameOver'}[this.mode];if(active===key&&!this.externalSource){const mode=this.mode;this.mode='silent';this.setMode(mode);}}),
   ...Object.entries(this.manifest.effects||{}).map(async([key,src])=>this.sampleFX[key]=await decode(src)),
   ...Object.entries(this.manifest.loops||{}).map(async([key,src])=>this.sampleLoops[key]=await decode(src))
  ]);
 }

 playSample(buffer,bus='sfx',gain=.6){if(!buffer||!this.ctx||this.ctx.state!=='running'||this.prefs.mute)return false;const s=this.ctx.createBufferSource(),g=this.ctx.createGain();s.buffer=buffer;g.gain.value=gain;s.connect(g).connect(this.buses[bus]);return this.track(s,g,buffer.duration,this.ctx.currentTime);}
 startStreamLoop(){const b=this.sampleLoops?.stream;if(!b||!this.ctx||this.ctx.state!=='running'||this.streamSource||this.prefs.mute||this.prefs.music===0)return;const s=this.ctx.createBufferSource(),g=this.ctx.createGain(),now=this.ctx.currentTime;s.buffer=b;s.loop=true;g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(.11,now+1.15);s.connect(g).connect(this.buses.music);s.start(now);s.onended=()=>{s.disconnect();g.disconnect();};this.streamSource=s;this.streamGain=g;}
 stopStreamLoop(fade=.65){if(!this.streamSource||!this.ctx)return;const s=this.streamSource,g=this.streamGain,now=this.ctx.currentTime;this.streamSource=null;this.streamGain=null;g.gain.cancelScheduledValues(now);g.gain.setTargetAtTime(.0001,now,Math.max(.015,fade/3));try{s.stop(now+Math.max(.04,fade));}catch{}}
 startLoop(id){const b=this.sampleLoops?.[['gas','chickenflight'].includes(id)?'rescue':id];if(!b)return ['afuera','rescue','gas','chickenflight'].includes(id)?super.startLoop(id):undefined;if(!this.ctx||this.loops.has(id)||this.ctx.state!=='running')return;const s=this.ctx.createBufferSource(),g=this.ctx.createGain();s.buffer=b;s.loop=true;g.gain.setValueAtTime(0,this.ctx.currentTime);g.gain.linearRampToValueAtTime(['rescue','gas','chickenflight'].includes(id)?.22:id==='afuera'?.28:.18,this.ctx.currentTime+.3);s.connect(g).connect(this.buses.sfx);s.start();this.loops.set(id,{s,g});}
 event(e){if(!this.ctx)return;const now=this.ctx.currentTime;if(e.type==='start'||e.type==='menu'){this.stopStreamLoop(.15);this.stopExternal(.2);this.stopLoops();this.mode='silent';if(e.type==='start')for(const n of [...this.nodes])try{n.stop();}catch{}}if(e.type==='chase'&&e.phase==='warning'){this.duck(.35);for(let i=0;i<3;i++)this.tone([440,554,659][i],.13,{gain:.075,at:now+i*.11});this.playSample(this.sampleFX?.siren,'sfx',.22);if(now-(this.lastCamera||0)>2){this.lastCamera=now;this.playSample(this.sampleFX?.camera,'sfx',.24);}return;}if(e.type==='chase'&&e.phase==='appearing'){this.startStreamLoop();this.playSample(this.sampleFX?.crowd,'ambience',.42);this.playSample(this.sampleFX?.[e.karina?'roastLaugh':'groupLaugh'],'voice',.44);return;}if(e.type==='chase'&&e.phase==='active'){this.playSample(this.sampleFX?.groupLaugh,'voice',.35);return;}if(e.type==='pressEscape'){this.tone(659,.14,{gain:.08});this.tone(988,.22,{gain:.08,at:now+.12});this.playSample(this.sampleFX?.roastLaugh,'sfx',.22);return;}if(e.type==='paperStorm'){this.playSample(this.sampleFX?.camera,'sfx',.18);return;}if(e.type==='deflect'){this.tone(740,.12,{gain:.06});return;}if(e.type==='news')this.playSample(this.sampleFX?.cameraClick,'sfx',.2);if(e.type==='near'&&now-(this.lastComedy||0)>5&&Math.random()<.42){this.lastComedy=now;this.playSample(this.sampleFX?.laugh,'sfx',.20);}if(e.type==='stumble'&&now-(this.lastComedy||0)>2){this.lastComedy=now;this.playSample(this.sampleFX?.bonk,'sfx',.32);this.playSample(this.sampleFX?.crowd,'ambience',.17);}const map={lane:'lane',jump:'jump',slide:'slide',land:'land',landing:'land',tp:'tp',dollar:'dollar',power:'power',powerEnd:'expire',stumble:'stumble',destroy:'destroy',fail:'fail',relief:'relief',ui:'tap',go:'countdown',powerWarning:'panic',rescueWarning:'panic',end:'cheer'};
  if(e.type==='power'){const p=BONUS_POWERS.find(p=>p.id===e.id);if(p){const n=BONUS_POWERS.indexOf(p),base=220+n*29;this.tone(base,.12,{gain:.045});this.tone(base*1.5,.16,{gain:.045,at:now+.09});this.tone(base*2,.18,{gain:.035,at:now+.18});}this.currentPower=e.id;this.startLoop(e.id);this.duck(.5);if(e.id==='afuera')this.voice('¡Afuera!');}if(e.type==='powerEnd'){this.currentPower=null;this.stopLoops();}if(e.type==='fail'){this.stopLoops();this.stopStreamLoop(.35);this.stopExternal();this.mode='silent';}if(e.type==='end')this.setMode('over');if(e.type==='go')this.setMode('running');if(e.type==='tp'&&this.ctx.currentTime-this.lastTP<.075)return;if(e.type==='tp')this.lastTP=this.ctx.currentTime;if(e.type==='relief')this.voice('¡Salvado!');
  const gains={tp:.32,dollar:.42,lane:.32,jump:.48,slide:.42,land:.40,stumble:.72,fail:.78,power:.58,expire:.32,tap:.38};if(!this.playSample(this.sampleFX?.[map[e.type]],e.type==='ui'?'ui':'sfx',gains[map[e.type]]??.5))super.event(e);
 }
 playExternal(buffer,loop,fadeIn=.25){return super.playExternal(buffer,loop,fadeIn);}
 stopLoops(){if(!this.ctx){super.stopLoops();return;}const now=this.ctx.currentTime;for(const l of this.loops.values()){l.g.gain.cancelScheduledValues(now);l.g.gain.setTargetAtTime(0,now,.12);for(const n of[l.s,l.o,l.mod])if(n){try{n.stop(now+.4);}catch{}n.onended=()=>{n.disconnect();for(const a of[l.g,l.mg,l.f])a?.disconnect();};}}this.loops.clear();}
 tick(engine){super.tick(engine);if(this.externalSource&&this.mode==='running')this.externalSource.playbackRate.setTargetAtTime(Math.min(1.08,1+Math.max(0,engine.speed-18)*.005),this.ctx.currentTime,.6);}
 introCue(shot){if(shot===1){const key=['speechMilei','speechTrump','speechBibi','speechBen'][this.prefs.character||0];this.lastSpeech={key,shot};this.duck(1.8);this.playSample(this.sampleFX?.[key],'voice',.82);return;}if(shot===0){this.setMode('intro');this.noise(.04,{bus:'ambience',gain:.08});return;}if(shot===2){this.playSample(this.sampleFX?.realization,'voice',.82);return;}if(shot===3){this.playSample(this.sampleFX?.escapeFootsteps,'sfx',.42);super.introCue(shot);return;}if(shot===4){this.playSample(this.sampleFX?.chaseShout,'voice',.72);return;}super.introCue(shot);}
 pause(){this.stopStreamLoop(.04);super.pause();}
 async resume(engine){await super.resume(engine);if(engine?.power)this.startLoop(engine.power);if(engine?.chase?.live)this.startStreamLoop();}
 dispose(){this.disposed=true;super.dispose();}
 snapshot(){return {...super.snapshot(),installedSamples:Object.values(this.sampleFX||{}).filter(Boolean).length+Object.values(this.sampleLoops||{}).filter(Boolean).length+Object.values(this.external).filter(Boolean).length,audioErrors:this.audioErrors||[],speech:this.lastSpeech||null,menuLoopSeconds:this.external.menuComedy?.duration||0};}
}
