import {DiaperAudio as LegacyAudio} from '../audio.js';
export class DiaperAudio extends LegacyAudio{
 async loadOptional(){this.manifest=await fetch(new URL('../audio/manifest-v3.json',import.meta.url)).then(r=>{if(!r.ok)throw Error('Audio manifest unavailable');return r.json();}).catch(()=>({}));}
 async decodeOptional(){if(!this.ctx||this.optionalLoaded)return;this.optionalLoaded=true;await this.loadOptional();this.sampleFX={};this.sampleLoops={};this.audioErrors=[];const decode=async(src)=>{try{const r=await fetch(new URL('../audio/'+src,import.meta.url));if(!r.ok)throw Error(src);return await this.ctx.decodeAudioData(await r.arrayBuffer());}catch{this.audioErrors.push(src);return null;}};
  await Promise.all([...[['circus','circus'],['gameOver','gameOver'],['intro','intro']].map(async([key,dest])=>{if(this.manifest[key])this.external[dest]=await decode(this.manifest[key]);}),...Object.entries(this.manifest.effects||{}).map(async([key,src])=>this.sampleFX[key]=await decode(src)),...Object.entries(this.manifest.loops||{}).map(async([key,src])=>this.sampleLoops[key]=await decode(src))]);const mode=this.mode;this.mode='silent';this.setMode(mode);
 }
 playSample(buffer,bus='sfx',gain=.6){if(!buffer||!this.ctx||this.ctx.state!=='running'||this.prefs.mute)return false;const s=this.ctx.createBufferSource(),g=this.ctx.createGain();s.buffer=buffer;g.gain.value=gain;s.connect(g).connect(this.buses[bus]);return this.track(s,g,buffer.duration,this.ctx.currentTime);}
 startLoop(id){const b=this.sampleLoops?.[id];if(!b)return ['afuera','rescue'].includes(id)?super.startLoop(id):undefined;if(!this.ctx||this.loops.has(id)||this.ctx.state!=='running')return;const s=this.ctx.createBufferSource(),g=this.ctx.createGain();s.buffer=b;s.loop=true;g.gain.setValueAtTime(0,this.ctx.currentTime);g.gain.linearRampToValueAtTime(id==='rescue'?.22:id==='afuera'?.28:.18,this.ctx.currentTime+.3);s.connect(g).connect(this.buses.sfx);s.start();this.loops.set(id,{s,g});}
 event(e){if(!this.ctx)return;const now=this.ctx.currentTime;if(e.type==='chase'&&e.phase==='warning'){this.duck(.35);for(let i=0;i<3;i++)this.tone([440,554,659][i],.13,{gain:.075,at:now+i*.11});this.playSample(this.sampleFX?.siren,'sfx',.22);if(now-(this.lastCamera||0)>2){this.lastCamera=now;this.playSample(this.sampleFX?.camera,'sfx',.24);}return;}if(e.type==='chase'&&e.phase==='appearing'){this.playSample(this.sampleFX?.crowd,'ambience',.42);this.playSample(this.sampleFX?.[e.karina?'roastLaugh':'groupLaugh'],'voice',.44);return;}if(e.type==='chase'&&e.phase==='active'){this.playSample(this.sampleFX?.groupLaugh,'voice',.35);return;}if(e.type==='pressEscape'){this.tone(659,.14,{gain:.08});this.tone(988,.22,{gain:.08,at:now+.12});this.playSample(this.sampleFX?.roastLaugh,'sfx',.22);return;}if(e.type==='news')this.playSample(this.sampleFX?.cameraClick,'sfx',.2);if(e.type==='near'&&now-(this.lastComedy||0)>5&&Math.random()<.42){this.lastComedy=now;this.playSample(this.sampleFX?.laugh,'sfx',.20);}if(e.type==='stumble'&&now-(this.lastComedy||0)>2){this.lastComedy=now;this.playSample(this.sampleFX?.bonk,'sfx',.32);this.playSample(this.sampleFX?.crowd,'ambience',.17);}const map={lane:'lane',jump:'jump',slide:'slide',land:'land',landing:'land',tp:'tp',dollar:'dollar',power:'power',powerEnd:'expire',stumble:'stumble',destroy:'destroy',fail:'fail',relief:'relief',ui:'tap',go:'countdown',powerWarning:'panic',rescueWarning:'panic',end:'cheer'};
  if(e.type==='power'){this.currentPower=e.id;this.startLoop(e.id);this.duck(.5);if(e.id==='afuera')this.voice('¡Afuera!');}if(e.type==='powerEnd'){this.currentPower=null;this.stopLoops();}if(e.type==='fail'){this.stopLoops();this.stopExternal();this.mode='silent';}if(e.type==='end')this.setMode('over');if(e.type==='go')this.setMode('running');if(e.type==='tp'&&this.ctx.currentTime-this.lastTP<.075)return;if(e.type==='tp')this.lastTP=this.ctx.currentTime;if(e.type==='relief')this.voice('¡Salvado!');
  const gains={tp:.32,dollar:.42,lane:.32,jump:.48,slide:.42,land:.40,stumble:.72,fail:.78,power:.58,expire:.32,tap:.38};if(!this.playSample(this.sampleFX?.[map[e.type]],e.type==='ui'?'ui':'sfx',gains[map[e.type]]??.5))super.event(e);
 }
 playExternal(buffer,loop){if(!this.ctx)return;const s=this.ctx.createBufferSource(),g=this.ctx.createGain();s.buffer=buffer;s.loop=loop;g.gain.setValueAtTime(0,this.ctx.currentTime);g.gain.linearRampToValueAtTime(.46,this.ctx.currentTime+.4);s.connect(g).connect(this.buses.music);s.onended=()=>g.disconnect();s.start();this.externalSource=s;}
 stopLoops(){if(!this.ctx){super.stopLoops();return;}const now=this.ctx.currentTime;for(const l of this.loops.values()){l.g.gain.cancelScheduledValues(now);l.g.gain.setTargetAtTime(0,now,.12);for(const n of[l.s,l.o,l.mod])if(n){try{n.stop(now+.4);}catch{}n.onended=()=>{n.disconnect();for(const a of[l.g,l.mg,l.f])a?.disconnect();};}}this.loops.clear();}
 tick(engine){super.tick(engine);if(this.externalSource&&this.mode==='running')this.externalSource.playbackRate.setTargetAtTime(Math.min(1.08,1+Math.max(0,engine.speed-18)*.005),this.ctx.currentTime,.6);}
 introCue(shot){if(shot===0&&this.external.intro){this.playSample(this.external.intro,'music',.75);return;}super.introCue(shot);}
 snapshot(){return {...super.snapshot(),installedSamples:Object.values(this.sampleFX||{}).filter(Boolean).length+Object.values(this.sampleLoops||{}).filter(Boolean).length+Object.values(this.external).filter(Boolean).length,audioErrors:this.audioErrors||[]};}
}
