export const COMMENTS=[['pablo.ok','JAJAJAJAJA 😂'],['sofi.mdp','NO PUEDE SER 💀'],['lucas_87','CORRÉ LEÓN 😭'],['mari_cba','ESA COLA 😭😭'],['mati.arg','POBRECITO 😂'],['agusss','MODO PAÑAL 🧻'],['flor.ok','DALE JAVO CORRÉ'],['tomi11','JAJAJAJA'],['nico.24','TE ALCANZAN 😂'],['juancho','SE TERMINÓ 💀'],['vale.ok','¿Y TU HERMANA? 🧻'],['martu','QUE VENGA A LIMPIARLO 😭'],['lean.arg','¿DÓNDE ESTÁ TRUMP? 😂'],['cami','EL EGO CORRE MÁS RÁPIDO'],['facu','VLLC 😂'],['rocio','NO MIRES ATRÁS 💀'],['fede','LA PRENSA TE ALCANZA 📸'],['nacho','CORRÉ CORRÉ CORRÉ'],['luli','POBRE LEÓN 🦁😭'],['gonza','OTRA VEZ EL PAÑAL 💀'],['dani','EL COLECTIVO NO FRENA 😭'],['mica','ÚLTIMO MOMENTO 🧻'],['santi','LA DIGNIDAD QUEDÓ ATRÁS 😂'],['lola','MIRÁ ESE SALTO 🔥']];
const CHAT_EMOJI=['😂','🤣','💀','😭','😂','💀'];
const icons={hit:['😂','😭','💩'],caught:['😂','📸','😭'],near:['🔥','👍'],lion:['🦁','🔥'],rescue:['❤️','👍'],pressure:['🧻','😂','😭'],escape:['🔥','❤️'],news:['😂','📰'],roof:['🔥','👏'],paper:['🧻','❤️']};
export class BroadcastUI{
 constructor(hud,prefs){this.prefs=prefs;this.root=document.createElement('div');this.root.id='broadcast';this.root.hidden=true;this.root.innerHTML='<div id="live-badge"><strong>● EN VIVO</strong><span>◉ <b></b></span></div><div id="press-warning"></div><div id="live-comments"></div><div id="live-reactions"></div>';hud.append(this.root);this.badge=this.root.querySelector('#live-badge');hud.querySelector('.resources').append(this.badge);this.warning=this.root.querySelector('#press-warning');this.commentBox=this.root.querySelector('#live-comments');this.reactionBox=this.root.querySelector('#live-reactions');this.comments=Array.from({length:4},()=>{const el=document.createElement('div');el.className='live-comment';el.innerHTML='<b></b><span></span>';this.commentBox.append(el);el.hidden=true;return {el,life:0};});this.reactions=Array.from({length:28},()=>{const el=document.createElement('i');this.reactionBox.append(el);el.hidden=true;return {el,life:0};});this.reset();}
 reset(){this.time=0;this.index=0;this.lastElapsed=0;this.cooldown=0;this.viewerText='';this.displayViewers=18400;this.reactionTick=0;this.frenzy=0;this.root.hidden=true;this.badge.hidden=true;for(const p of[...this.comments,...this.reactions]){p.life=0;p.el.hidden=true;}this.warning.textContent='';this.warningTimer=0;}
 comment(kind){const free=this.comments.find(p=>p.life<=0)||this.comments.reduce((a,b)=>a.life<b.life?a:b);const pool=kind==='lion'?[18,22]:kind==='hit'?[0,1,3,5,20]:kind==='caught'?[8,9,16]:kind==='pressure'?[5,10,11,19]:kind==='roof'?[23,20]:kind==='rescue'?[14,17]:kind==='escape'?[12,22]:kind==='paper'?[5,21]:null;const i=pool?pool[this.index++%pool.length]:this.index++%COMMENTS.length;const[u,msg]=COMMENTS[i];free.el.querySelector('b').textContent=u;free.el.querySelector('span').textContent=msg;free.life=2.2;free.serial=this.index;this.commentBox.append(free.el);free.el.hidden=false;}
 burst(kind){const list=['hit','caught','pressure','run'].includes(kind)?CHAT_EMOJI:icons[kind]||CHAT_EMOJI;const count=this.prefs.motion?kind==='hit'||kind==='caught'?14:kind==='run'?2:7:1;for(let i=0;i<count;i++){const p=this.reactions.find(p=>p.life<=0);if(!p)break;p.life=1.5+(i%5)*.08;p.total=p.life;p.x=-((this.index+i)%4)*9;p.sway=(this.index+i)%2?1:-1;p.el.textContent=list[i%list.length];p.el.hidden=false;}}
 event(e){if(['start','menu'].includes(e.type)){this.reset();return;}if(e.type==='land'&&this.cooldown<=0){this.comment('roof');this.burst('roof');this.cooldown=.35;this.frenzy=2.5;}if(e.type==='relief'){this.comment('paper');this.burst('paper');this.cooldown=.35;this.frenzy=2.5;}if(e.type==='broadcast'){this.comment(e.kind);this.burst(e.kind);this.cooldown=.35;this.frenzy=2.5;}if(e.type==='chase'){if(e.phase==='warning'){this.warning.textContent=e.karina?'¡VIENE KARINA!':'¡SE VIENE LA PRENSA!';this.warningTimer=2;}if(e.phase==='active'&&e.gap<=4.25){this.warning.textContent='¡OTRO GOLPE Y TE ATRAPAN!';this.warningTimer=2;}if(e.phase==='caught'){this.warning.textContent='¡TE AGARRÓ LA PRENSA!';this.warningTimer=1;}}}
 update(e,dt){const c=e.chase;if(!c)return;const playing=['RUNNING','IMPACT','COUNTDOWN','PAUSED'].includes(e.state);this.root.hidden=!playing||!c.live&&c.state!=='warning';this.badge.hidden=!playing||!c.live;if(this.root.hidden)return;const frozen=['PAUSED','COUNTDOWN'].includes(e.state);dt=frozen?0:dt;this.time+=dt;this.cooldown-=dt;this.warningTimer=Math.max(0,this.warningTimer-dt);this.warning.hidden=this.warningTimer===0;this.root.classList.toggle('press-close',c.gap<=4.25&&c.state==='active');this.displayViewers+=(c.viewerCount-this.displayViewers)*Math.min(1,dt*3);const v=(this.displayViewers/1000).toFixed(1)+'K';if(v!==this.viewerText){this.badge.querySelector('b').textContent=v;this.viewerText=v;}
 if(c.live&&this.cooldown<=0&&e.state==='RUNNING'){this.comment('run');this.cooldown=this.prefs.motion?(this.frenzy>0?.22:.48):1.4;}
 this.frenzy=Math.max(0,this.frenzy-dt);this.reactionTick-=dt;if(c.live&&e.state==='RUNNING'&&this.reactionTick<=0){this.burst('run');this.reactionTick=this.prefs.motion?(this.frenzy>0?.10:.20):1.2;}
 for(const p of this.comments){p.life=Math.max(0,p.life-dt);p.el.hidden=p.life===0;p.el.style.opacity=String(Math.min(1,p.life*2.5));}
 for(const p of this.reactions){p.life=Math.max(0,p.life-dt);p.el.hidden=p.life===0;const age=p.total-p.life;p.el.style.transform=`translate(${p.x+Math.sin(age*3)*7*p.sway}px,${-age*85}px)`;p.el.style.opacity=String(Math.min(1,p.life*2));}
 if(this.layoutPower!==e.power||!this.layoutReady){const bottom=document.querySelector('.hud-bottom');this.commentBox.style.bottom=(bottom.offsetHeight+22)+'px';this.layoutPower=e.power;this.layoutReady=true;}}
 snapshot(){return {comments:this.comments.filter(p=>p.life>0).length,reactions:this.reactions.filter(p=>p.life>0).length,nodes:4+28};}
}
