// User-authored live chat. Pools are isolated by runner; IDs preserve saved progress.
export const CHARACTER_CHAT=Object.freeze({
 trump:[
  ['alex',"SUPER INTELLIGENCE COULDN'T SAVE THAT DODGE 🤖😭"],
  ['leo','ASK THE AI WHICH LANE TO USE BRO 💀'],
  ['max','CHATGPT PREDICTED THIS CRASH 😭'],
  ['sam','BRO NEEDS ARTIFICIAL INTELLIGENCE AND NATURAL INTELLIGENCE'],
  ['fede','THE AI SAID RETIRE 😭'],['tomi','RETIRE OLD MAN 💀'],
  ['nico','SELLOUT SPEEDRUN ANY%'],['juan','COWARD MODE ACTIVATED 🐷'],
  ['mati','ANTI-AMERICA DLC UNLOCKED 🇺🇸💀'],['nacho','BRO SOLD THE WHOLE LOBBY 😭'],
  ['luli','PRESIDENTIAL PANIC MODE'],['agus','EVEN THE AI IS RUNNING FROM HIM 🤖'],
  ['max','SUPERINTELLIGENCE: TURN LEFT — HIM: 🚌💥'],
  ['leo','THE ALGORITHM HAS DECLARED HIM COOKED'],['fede','RETIREMENT HOME FINAL BOSS 💀'],
  ['nico','EL CERDO SE ESCAPÓ 😭🐷'],['mati','MAKE DIAPERS GREAT AGAIN 🇺🇸'],
  ['juan','FAKE NEWS!!! *HITS A BUS*'],['nacho','THIS RUN WILL BE TREMENDOUS'],
  ['tomi','NOBODY RUNS BETTER, BELIEVE ME']
 ],
 bibi:[
  ['yossi',"BRO THINKS HE'S THE CHOSEN ONE 😭"],
  ['avi','KING BIBI HAS LEFT THE BUILDING 👑💀'],['noam',"EVEN THE IRON DOME CAN'T BLOCK THAT BUS 😭"],
  ['dani','BIBI BIBI MODE ACTIVATED 💀'],['maya','THE CROWN IS DOING ALL THE WORK 👑'],
  ['eli','SUPER INTELLIGENCE SAID TURN LEFT BRO 🤖'],['noam','ASK THE AI HOW TO DODGE 😭'],
  ['avi','BRO HAS 99 POLITICAL LIVES'],['dani','RETIREMENT DLC STILL LOCKED 💀'],
  ['maya',"HE'S BEEN IN THE LOBBY SINCE 1996 😭"],['eli','VICTIM CARD ACTIVATED 🃏'],
  ['yossi','THE CHOSEN FLIGHT ✈️😭'],['noam','BIBI AIRLINES HAS NO LANDING PLAN 💀'],
  ['avi','KING OF THE CHECKPOINT 👑'],['maya','BRO CAMPAIGNS BETWEEN OBSTACLES 😭'],
  ['dani','ANOTHER ELECTION SHOULD FIX IT 💀'],['eli','THE AI CALLED FOR EARLY ELECTIONS 🤖'],
  ['avi','THAT DIAPER HAS A COALITION MAJORITY 😭']
 ],
 ben:[
  ['dani',"TOUGH GUY ONLY AGAINST PEOPLE WHO CAN'T FIGHT BACK? 💀"],
  ['avi','BRO GOT MAD READING ONE COMMENT 😭'],['noam','COWARD MODE ACTIVATED 🐔'],
  ['maya',"HE'S TYPING A RESPONSE WHILE RUNNING 💀"],['eli',"BEN DON'T READ THE COMMENTS 😭"],
  ['avi',"THE CHICKENS CAN'T SAVE YOUR REPUTATION 🐔💀"],['noam','BIG BEN, TINY TEMPER 😭'],
  ['maya','HE SAW “COWARD” AND LOST 40 HP'],['eli',"JESUS IS THE MESSIAH — DON'T GET MAD BRO 😭"],
  ['dani','CHRIST IS KING ✝️ *BEN JR STARTS TYPING*'],['avi',"BRO PLEASE IT'S JUST A COMMENT SECTION 💀"],
  ['noam','KING DAVID WATCHING THIS RUN LIKE 👀'],['maya','DAVID FOUGHT GOLIATH — BEN FOUGHT A TRAFFIC CONE 😭'],
  ['eli','DAVID HAD A SLING. BEN HAS A CHICKEN DRONE 🐔'],
  ['dani','HE CALLED THE CHICKEN BECAUSE CHAT HURT HIS FEELINGS 💀']
 ]
});
