import * as T from './vendor/three.module.min.js';
import {buildPower,buildProp,bake} from './models.js';
import {supportAt,LANE_WIDTH} from './track.js';
import {VISUAL_STAIN_START,VISUAL_LEAK_START,visualPressure} from './pressure.js';
import {materialName} from './rig-materials.js';

const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
// All effects are bounded pools. Animation advances with the presentation clock,
// so pausing freezes both the particles and the appearance of the diaper.
function plumeMaterial(smoke=false){return new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,blending:smoke?T.NormalBlending:T.AdditiveBlending,uniforms:{time:{value:0},smoke:{value:smoke?1:0}},vertexShader:`varying vec2 v; uniform float time; void main(){v=uv; vec3 p=position; p.x+=sin(p.y*5.0+time*7.0)*.09*uv.y; gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.0);}`,fragmentShader:`varying vec2 v; uniform float time; uniform float smoke; void main(){float wiggle=sin(v.y*16.0-time*8.0)*.12; float width=mix(.46,.015,v.y); float edge=1.0-smoothstep(width*.3,width,abs(v.x-.5+wiggle*v.y)); float a=edge*(1.0-v.y)*smoothstep(0.0,.12,v.y); vec3 fire=mix(vec3(1.0,.13,.008),vec3(1.0,.82,.14),1.0-v.y); gl_FragColor=vec4(mix(fire,vec3(.20,.23,.25),smoke),a*mix(.8,.35,smoke));}`});}
function makeLionManeTexture(){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d');const g=x.createRadialGradient(256,245,48,256,256,278);g.addColorStop(0,'#f5b936');g.addColorStop(.46,'#ad5319');g.addColorStop(1,'#43221b');x.fillStyle=g;x.fillRect(0,0,512,512);for(let i=0;i<52;i++){const a=i*Math.PI*2/52,inner=172+(i%4)*7,outer=246+(i%5)*8;x.save();x.translate(256,256);x.rotate(a);x.beginPath();x.moveTo(-18,inner);x.bezierCurveTo(-34,inner-32,-25,outer-22,0,outer);x.bezierCurveTo(20,outer-24,31,inner-26,18,inner);x.closePath();const f=x.createLinearGradient(-20,0,20,0);f.addColorStop(0,'#612b14');f.addColorStop(.45,i%3?'#f5ad28':'#ffd45a');f.addColorStop(1,'#8e3c15');x.fillStyle=f;x.fill();x.restore();}x.save();x.translate(256,252);x.scale(1,.92);const face=x.createRadialGradient(-35,-40,12,0,0,160);face.addColorStop(0,'#f6d070');face.addColorStop(.68,'#c57724');face.addColorStop(1,'#70331b');x.fillStyle=face;x.beginPath();x.ellipse(0,0,139,157,0,0,Math.PI*2);x.fill();x.fillStyle='#482219';for(const s of[-1,1]){x.beginPath();x.ellipse(s*74,-112,42,50,s*.3,0,Math.PI*2);x.fill();x.fillStyle='#e6a842';x.beginPath();x.ellipse(s*74,-106,24,29,s*.3,0,Math.PI*2);x.fill();x.fillStyle='#482219';x.beginPath();x.ellipse(s*52,-17,29,20,0,0,Math.PI*2);x.fill();x.fillStyle='#ffe967';x.beginPath();x.ellipse(s*52,-18,17,11,0,0,Math.PI*2);x.fill();x.fillStyle='#261617';x.beginPath();x.ellipse(s*52,-18,5,10,0,0,Math.PI*2);x.fill();x.fillStyle='#482219';}x.fillStyle='#472019';x.beginPath();x.moveTo(-25,34);x.quadraticCurveTo(0,13,25,34);x.quadraticCurveTo(0,56,-25,34);x.fill();x.fillStyle='#f2c46b';x.beginPath();x.ellipse(0,71,54,41,0,0,Math.PI*2);x.fill();x.fillStyle='#49211b';x.beginPath();x.moveTo(-20,56);x.quadraticCurveTo(0,42,20,56);x.quadraticCurveTo(0,72,-20,56);x.fill();x.strokeStyle='#49211b';x.lineWidth=8;x.beginPath();x.moveTo(0,70);x.lineTo(0,105);x.quadraticCurveTo(-24,129,-43,112);x.moveTo(0,105);x.quadraticCurveTo(24,129,43,112);x.stroke();x.restore();const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;tex.anisotropy=4;return tex;}
function instances(scene,geometry,mat,count){const m=new T.InstancedMesh(geometry,mat,count);m.count=0;m.frustumCulled=false;m.instanceMatrix.setUsage(T.DynamicDrawUsage);scene.add(m);return m;}
export class RunnerEffects{
 constructor(renderer){this.r=renderer;this.scene=renderer.scene;this.hair=[];this.stains=[];this.soles=[];this.bones={};this.clock=0;this.dummy=new T.Object3D();this.v=new T.Vector3();this.drops=Array.from({length:64},()=>({active:false}));this.splats=Array.from({length:24},()=>({active:false}));this.sparks=Array.from({length:64},()=>({active:false}));this.dripDebt=0;this.sparkDebt=0;this.lionTexture=makeLionManeTexture();this.lionManeReady=null;
  this.fire=new T.Group();this.flameMaterial=plumeMaterial();for(let i=0;i<16;i++){const m=new T.Mesh(new T.PlaneGeometry(.65,1.3,1,8),this.flameMaterial);const a=i*Math.PI*2/16;m.position.set(Math.sin(a)*.48,.04+Math.cos(i)*.06,Math.cos(a)*.44);m.scale.set(.9,.7,1);m.rotation.y=a;m.rotation.z=Math.sin(i)*.23;this.fire.add(m);}this.fire.visible=false;
  this.smokeMaterial=plumeMaterial(true);this.smoke=instances(this.scene,new T.PlaneGeometry(1,1.8,1,5),this.smokeMaterial,20);
  this.sparkMesh=instances(this.scene,new T.SphereGeometry(1,6,4),new T.MeshBasicMaterial({color:0xffd25a}),64);
  this.dropMesh=instances(this.scene,new T.SphereGeometry(1,10,6),new T.MeshStandardMaterial({color:0x714221,roughness:.5}),64);
  this.splatMesh=instances(this.scene,new T.SphereGeometry(1,10,5),new T.MeshStandardMaterial({color:0x54351e,roughness:.85}),24);
  this.bills=instances(this.scene,new T.BoxGeometry(.50,.012,.25),new T.MeshStandardMaterial({color:0x83d16d,emissive:0x2c631b,emissiveIntensity:.6,roughness:.6}),24);
  this.billBands=instances(this.scene,new T.BoxGeometry(.10,.017,.255),new T.MeshBasicMaterial({color:0xf5e7ba}),24);
  this.magnet=buildPower('magnet');this.magnet.scale.setScalar(1.8);this.scene.add(this.magnet);this.magnet.visible=false;
  this.paper=new T.Group();for(const part of bake(buildProp('tp')))this.paper.add(instances(this.paper,part.geometry,part.material,6));this.paperParts=this.paper.children.filter(o=>o.isInstancedMesh);this.scene.add(this.paper);
  this.seep=new T.Group();const brown=new T.MeshStandardMaterial({color:0x75461f,roughness:.65});for(const side of [-1,1])for(let i=0;i<4;i++){const m=new T.Mesh(new T.SphereGeometry(1,10,6),brown);m.position.set(side*(.32+i*.027),-.02-i*.05,-.32);m.scale.set(.065,.085,.035);this.seep.add(m);}this.seep.visible=false;
 }
 loadLionMane(){if(!this.lionManeReady)this.lionManeReady=new T.TextureLoader().loadAsync(new URL('../art/lion-mane-back.webp',import.meta.url).href).then(tex=>{tex.colorSpace=T.SRGBColorSpace;tex.anisotropy=Math.min(4,this.r.gl.capabilities.getMaxAnisotropy());this.lionTexture.dispose();this.lionTexture=tex;return tex;}).catch(()=>this.lionTexture);return this.lionManeReady;}
 bind(hero){this.hair=[];this.stains=[];this.soles=[];this.bodyContact=[];this.bones={};hero.traverse(o=>{if(o.isBone)this.bones[o.name]=o;if(!o.isMesh)return;if(o.isSkinnedMesh&&materialName(o.material)!=='rear hair detail'){const p=o.geometry.attributes.position;this.bodyContact.push({mesh:o,indices:Array.from({length:Math.ceil(p.count/Math.max(1,Math.floor(p.count/600)))},(_,i)=>i*Math.max(1,Math.floor(p.count/600))).filter(i=>i<p.count)});}for(const m of Array.isArray(o.material)?o.material:[o.material]){if(['chestnut hair','hair highlights','rear hair detail'].includes(materialName(m))){this.hair.push({m,mesh:o,color:m.color.clone(),baseMap:m.map});if(materialName(m)==='rear hair detail'){m.emissiveMap=m.map;m.alphaTest=.4;m.transparent=false;m.depthWrite=true;m.needsUpdate=true;}}if(materialName(m)==='diaper cotton'){
   // Stain is evaluated in rest-space before skinning, so it follows every
   // fold and the pelvis rather than floating over the running character.
   m.userData.pressure={value:0};m.onBeforeCompile=s=>{s.uniforms.diaperPressure=m.userData.pressure;s.vertexShader='uniform float diaperPressure; varying vec3 cottonPosition;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\ncottonPosition=position; float fill=clamp((diaperPressure-15.0)/85.0,0.0,1.0); float puff=smoothstep(.65,.95,position.y)*(1.0-smoothstep(1.15,1.38,position.y)); transformed.x*=1.0+.18*fill*puff; transformed.z*=1.0+.24*fill*puff; transformed.y-=.10*fill*puff;');s.fragmentShader='varying vec3 cottonPosition; uniform float diaperPressure;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
    float pressure=clamp((diaperPressure+5.0)/100.0,0.0,1.0);
    vec3 cp=cottonPosition; float rear=smoothstep(.08,.27,abs(cp.z));
    float edge=sin(cp.x*39.0+cp.y*17.0)*.018+sin(cp.y*58.0-cp.x*22.0)*.012;
    vec2 q=vec2(cp.x/(.16+pressure*.46),(cp.y-(1.07-pressure*.07))/(.12+pressure*.34));
    float stain=(1.0-smoothstep(.68,1.12,length(q)+edge*4.0))*rear*pressure;
    vec3 brown=mix(vec3(.36,.19,.075),vec3(.22,.105,.035),pressure);
    float fibre=sin(cp.y*620.0)*sin(cp.x*490.0)*.022;
    diffuseColor.rgb=mix(diffuseColor.rgb*(1.0+fibre),brown,min(1.0,stain*1.45));
   `);};m.customProgramCacheKey=()=>'cotton-pressure-v4';m.needsUpdate=true;this.stains.push(m);
  }if(materialName(m)==='rubber'&&o.isSkinnedMesh){const p=o.geometry.attributes.position;let min=Infinity;for(let i=0;i<p.count;i++)min=Math.min(min,p.getY(i));const indices=[];for(let i=0;i<p.count;i++)if(p.getY(i)<min+.035)indices.push(i);this.soles.push({mesh:o,indices:indices.filter((_,i)=>i%Math.max(1,Math.floor(indices.length/48))===0)});}}});
  // Bone local Y follows its length; the rear cotton sits behind local -Z.
  this.baseHeadScale=this.bones.head?.scale.clone();this.bones.pelvis?.add(this.seep);if(this.bones.head){this.bones.head.add(this.fire);this.fire.position.set(0,.02,0);}else hero.add(this.fire);
 }
 mountImpactHead(hero,textures){this.impactTextures=textures;this.headUniforms={headExpression:{value:textures[0]},headReaction:{value:0},headHair:{value:this.hair.find(h=>materialName(h.m)==='rear hair detail')?.m.map}};
  // Rest-space surface shading follows the actual skinned skull. No extra
  // portrait mesh, independent tilt, replacement head, or screen-space mask.
  const names=new Set(['warm peach','eyes','blue iris','mouth','lips','chestnut hair','polished leather']);hero.traverse(o=>{if(!o.isMesh)return;for(const m of Array.isArray(o.material)?o.material:[o.material]){if(!names.has(materialName(m)))continue;m.onBeforeCompile=s=>{Object.assign(s.uniforms,this.headUniforms);s.vertexShader='varying vec3 headRest;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nheadRest=position;');s.fragmentShader='varying vec3 headRest; uniform sampler2D headExpression; uniform sampler2D headHair; uniform float headReaction;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
    vec3 hp=headRest;
    float skull=smoothstep(2.08,2.18,hp.y);
    ${['eyes','blue iris','mouth','lips','polished leather'].includes(materialName(m))?'if(headReaction>.05&&skull>.9&&hp.z>.04)discard;':''}
    vec2 faceUV=vec2(hp.x/1.22+.5,(hp.y-2.07)/1.10);
    vec4 face=texture2D(headExpression,clamp(faceUV,0.0,1.0));
    float front=smoothstep(.04,.30,hp.z)*skull*(1.0-smoothstep(3.10,3.22,hp.y));
    diffuseColor.rgb=mix(diffuseColor.rgb,face.rgb,headReaction*front*face.a);
    vec2 hairUV=vec2(hp.x/1.8+.5,(hp.y-2.015)/1.73);
    vec4 mane=texture2D(headHair,clamp(hairUV,0.0,1.0));
    float crown=smoothstep(2.91,3.08,hp.y);
    diffuseColor.rgb=mix(diffuseColor.rgb,mane.rgb,crown*mane.a*headReaction);
   `);};m.customProgramCacheKey=()=>'skull-mounted-expression-v2';m.needsUpdate=true;}});
 }
 floorY(fullBody=false){let min=Infinity;for(const {mesh,indices}of(fullBody||!this.soles.length?this.bodyContact:this.soles)){mesh.skeleton.update();for(const i of indices){this.v.fromBufferAttribute(mesh.geometry.attributes.position,i);mesh.applyBoneTransform(i,this.v);mesh.localToWorld(this.v);min=Math.min(min,this.v.y);}}return min;}
 handCenter(out){const l=this.bones.hand_L,r=this.bones.hand_R;if(!l||!r)return out.copy(this.r.heroRoot.position).add(new T.Vector3(0,2.3,0));l.getWorldPosition(out);r.getWorldPosition(this.v);return out.add(this.v).multiplyScalar(.5);}
 reset(){for(const pool of [this.drops,this.splats,this.sparks])for(const p of pool)p.active=false;this.dripDebt=this.sparkDebt=0;}
 event(e){if(e.type==='start'||e.type==='menu')this.reset();if(e.type==='destroy')this.emitSparks(e.lane*3.2,1.3,-(e.z||5),28);}
 emitSparks(x,y,z,n){for(let i=0;i<n;i++){const p=this.sparks.find(p=>!p.active);if(!p)break;const a=Math.random()*Math.PI*2;Object.assign(p,{active:true,x,y,z,vx:Math.cos(a)*4,vy:2+Math.random()*4,vz:Math.sin(a)*4,life:.4+Math.random()*.3});}}
 leak(position,risk=70){const p=this.drops.find(p=>!p.active);if(!p)return;const severity=clamp((risk-25)/75);Object.assign(p,{active:true,x:position.x+(Math.random()-.5)*(.22+severity*.34),y:position.y+.04,z:position.z+.12,vx:(Math.random()-.5)*(.35+severity*.45),vy:-.2-severity*.35,vz:.4,life:1.7+severity*.7,size:.11+severity*.15+Math.random()*.035});}
 update(e,dt,x,y,menu){this.clock+=dt;this.flameMaterial.uniforms.time.value=this.smokeMaterial.uniforms.time.value=this.clock;const lion=e.power==='lion',magnet=e.power==='magnet',money=e.power==='dollars',saw=e.power==='afuera';if(lion&&!this.lionManeReady)this.loadLionMane();const scale=this.r.heroScale||1;const risk=menu?0:visualPressure(e.meter,e.elapsed);const dirty=clamp((risk-VISUAL_STAIN_START)/(100-VISUAL_STAIN_START));for(const m of this.stains)m.userData.pressure.value=menu?-5:risk;this.seep.visible=risk>82&&!menu;this.seep.scale.setScalar(this.seep.visible?.55+clamp((risk-82)/18)*.8:0);
  if(this.headUniforms){this.headUniforms.headReaction.value=this.r.failed?1:this.r.stumble>0?Math.min(1,this.r.stumble/.08):0;this.headUniforms.headExpression.value=this.impactTextures[this.r.failed?1:0];}
  if(this.bones.head&&this.baseHeadScale)this.bones.head.scale.copy(this.baseHeadScale).multiplyScalar(lion?2:1);this.fire.scale.setScalar(lion?0.5:1);for(const {m,color,baseMap}of this.hair){const target=materialName(m)==='rear hair detail'&&lion?this.lionTexture:baseMap;if(m.map!==target){m.map=target;m.emissiveMap=target;m.needsUpdate=true;}m.color.copy(color);m.emissive.setHex(lion?0xff7910:0);m.emissiveMap=target||null;m.emissiveIntensity=lion?(target ? .62 : .7):0;if(lion&&materialName(m)==='rear hair detail')m.color.setHex(0xffd18a);else if(lion)m.color.setHex(m.map?0xffdc9c:0xf2ae26);}this.fire.visible=lion;
  if(!menu&&dt>0&&risk>=VISUAL_LEAK_START){const rate=risk<50?1.8:risk<75?4:risk<90?8: risk<98?12:16;this.dripDebt+=dt*rate;const pelvis=this.bones.pelvis;const rear=pelvis?pelvis.localToWorld(new T.Vector3(0,.02,-.33)):new T.Vector3(x,y+1,.4);while(this.dripDebt>=1){this.leak(rear,risk);this.dripDebt--;}}
  if(saw&&dt>0){this.sparkDebt+=dt*18;while(this.sparkDebt>=1){this.emitSparks(this.r.chainsaw.position.x+.3,this.r.chainsaw.position.y+.25,this.r.chainsaw.position.z-.1,1);this.sparkDebt--;}}
  this.magnet.visible=magnet;if(magnet){this.magnet.position.set(x,y+2.9*scale,.1);this.magnet.rotation.set(0,Math.sin(this.clock*2)*.25,Math.sin(this.clock*3)*.1);}
  for(const m of this.paperParts){m.count=magnet?6:0;if(magnet)for(let i=0;i<6;i++){const a=this.clock*2.8+i*Math.PI/3;this.dummy.position.set(x+Math.sin(a)*1.25,y+1.8*scale+Math.cos(a*2)*.3,Math.cos(a)*1.1);this.dummy.rotation.set(.2,a,0);this.dummy.scale.setScalar(.48);this.dummy.updateMatrix();m.setMatrixAt(i,this.dummy.matrix);}m.instanceMatrix.needsUpdate=true;}
  for(const m of [this.bills,this.billBands]){m.count=money?24:0;if(money)for(let i=0;i<24;i++){const t=(this.clock*.7+i*.143)%1,a=i*2.399+this.clock*.3;this.dummy.position.set(x+Math.sin(a)*(1.0+t*1.8),y+(4-t*3.4)*scale,Math.cos(a)*(1+t));this.dummy.rotation.set(Math.sin(this.clock*3+i)*.7,a,this.clock+i);this.dummy.scale.setScalar(1);this.dummy.updateMatrix();m.setMatrixAt(i,this.dummy.matrix);}m.instanceMatrix.needsUpdate=true;}
  this.smoke.count=lion?20:0;if(lion)for(let i=0;i<20;i++){const t=(this.clock*.8+i*.097)%1;this.dummy.position.set(x+Math.sin(i*2.4)*(.3+t),y+.5+t*1.5,1+t*5);this.dummy.rotation.set(0,0,Math.sin(i)*.4);this.dummy.scale.setScalar(.3+t*.9);this.dummy.updateMatrix();this.smoke.setMatrixAt(i,this.dummy.matrix);}this.smoke.instanceMatrix.needsUpdate=true;
  let count=0;for(const p of this.drops){if(!p.active)continue;p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy-=10*dt;p.z+=(e.speed+p.vz)*dt;const support=supportAt(e.pool.items,p.x/LANE_WIDTH,p.z);if(p.y<=support+.065){p.active=false;const s=this.splats.find(s=>!s.active)||this.splats[0];Object.assign(s,{active:true,x:p.x,y:support+.04,z:p.z,life:1.8,size:p.size*2.4});continue;}if(p.life<=0){p.active=false;continue;}this.dummy.position.set(p.x,p.y,p.z);this.dummy.rotation.set(0,0,0);this.dummy.scale.set(p.size,p.size*1.8,p.size);this.dummy.updateMatrix();this.dropMesh.setMatrixAt(count++,this.dummy.matrix);}this.dropMesh.count=count;this.dropMesh.instanceMatrix.needsUpdate=true;
  count=0;for(const p of this.splats){if(!p.active)continue;p.life-=dt;p.z+=e.speed*dt;if(p.life<=0){p.active=false;continue;}this.dummy.position.set(p.x,p.y??.04,p.z);this.dummy.rotation.set(0,0,0);const fade=Math.min(1,p.life/.55);this.dummy.scale.set(p.size*fade,.035*fade,p.size*1.65*fade);this.dummy.updateMatrix();this.splatMesh.setMatrixAt(count++,this.dummy.matrix);}this.splatMesh.count=count;this.splatMesh.instanceMatrix.needsUpdate=true;
  count=0;for(const p of this.sparks){if(!p.active)continue;p.life-=dt;if(p.life<=0){p.active=false;continue;}p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.vy-=8*dt;this.dummy.position.set(p.x,p.y,p.z);this.dummy.rotation.set(0,0,0);this.dummy.scale.set(.025,.025,.15*Math.min(1,p.life*4));this.dummy.updateMatrix();this.sparkMesh.setMatrixAt(count++,this.dummy.matrix);}this.sparkMesh.count=count;this.sparkMesh.instanceMatrix.needsUpdate=true;
  this.stats={impactHead:!!this.headUniforms&&this.headUniforms.headReaction.value>0,headState:this.r.failed?'crash':this.r.stumble>0?'hit':'none',dirtyOpacity:dirty,pressure:risk,stainReceiver:this.stains.length,seep:this.seep.visible,drops:this.dropMesh.count,splats:this.splatMesh.count,flames:this.fire.visible,lionHeadAttached:this.fire.parent===this.bones.head,lionHeadScale:this.baseHeadScale&&this.bones.head?this.bones.head.scale.x/this.baseHeadScale.x:1,lionTexture:this.hair.some(h=>materialName(h.m)==='rear hair detail'&&h.m.map===this.lionTexture),magnet:this.magnet.visible,bills:this.bills.count,sparks:this.sparkMesh.count};
 }
 dispose(){for(const {m,baseMap}of this.hair){m.map=baseMap;m.emissiveMap=baseMap||null;}this.lionTexture.dispose();}
}
