import {coverReady} from './cover.js';
import {RunnerEngine,STATES,POWERS,meterBand} from './engine.js';
import {CHARACTERS,characterAt,isUnlocked,BONUS_POWERS} from './characters.js';
const POWER_ICONS={magnet:'power-0.webp',lion:'power-cat-v2.webp',afuera:'power-chainsaw-v2.webp',dollars:'power-3.webp',rescue:'power-helicopter-v2.webp'};
import {CharacterSelector} from './selector.js';
import {RunnerRenderer} from './renderer.js';
import {BroadcastUI} from './broadcast.js';
import {DiaperAudio} from './audio.js';
import {readSave,writeSave} from './storage.js';
const $=s=>document.querySelector(s),all=s=>document.querySelectorAll(s),game=$('#game');
for(const p of BONUS_POWERS)POWER_ICONS[p.id]='power-'+p.id+'.webp';
POWER_ICONS.gas='trump-helicopter-v2.webp';POWER_ICONS.chickenflight='ben-chicken-drone-v2.webp';
const saved=readSave(),prefs=saved.prefs,assets={};const localPreview=['localhost','127.0.0.1'].includes(location.hostname),query=new URLSearchParams(location.search),testCharacterMode=localPreview&&query.get('testCharacters')==='1',previewCharacter=localPreview?CHARACTERS.find(c=>c.id===query.get('previewCharacter')):null;if(testCharacterMode)saved.progress.unlocked=Object.fromEntries(CHARACTERS.map(c=>[c.id,true]));if(previewCharacter)prefs.character=previewCharacter.index;if(!testCharacterMode&&!isUnlocked(saved.progress,prefs.character))prefs.character=0;const bootStarted=performance.now();
const audio=new DiaperAudio(prefs);const broadcast=new BroadcastUI($('#hud'),prefs);let renderer,screen='boot',dialogReturn='menu',lastTime=0,raf=0,uiTime=0,introShot=-1,toastTimer=0,shareUrl='',shareBlob=null,shareVersion=0,business='',locationName='',shareLink=location.href,calloutTimer=0,countLast='',lastBand=-1,dead=false,lastHud={},frameSamples=[],loadErrors=[];
const unlockAudioFromGesture=()=>{void audio.unlock();};window.addEventListener('pointerdown',unlockAudioFromGesture,{capture:true,once:true});window.addEventListener('keydown',unlockAudioFromGesture,{capture:true,once:true});
const engine=new RunnerEngine({seed:crypto.getRandomValues(new Uint32Array(1))[0],progress:saved.progress,onEvent:onEvent});engine.characterIndex=prefs.character;engine.difficulty=prefs.difficulty;
const I18N={es:{run:'¡A CORRER!',characters:'PERSONAJES',records:'RÉCORDS',achievements:'LOGROS',donate:'APOYAR',how:'¿CÓMO SE JUEGA?',distance:'DISTANCIA',paused:'PAUSADO',safe:'Tu carrera está a salvo. Por ahora.',resume:'▶ SEGUIR CORRIENDO',restart:'↻ RESTART',settings:'CONFIGURACIÓN',menu:'⌂ MENÚ PRINCIPAL',bestCombo:'MEJOR COMBO',record:'RÉCORD',share:'↗ COMPARTIR',music:'MÚSICA',voice:'VOZ',mute:'SILENCIAR TODO',reduced:'MOVIMIENTO REDUCIDO',haptics:'VIBRACIÓN',language:'IDIOMA',reset:'BORRAR PROGRESO',resetConfirm:'¿Borrar récords, papel y logros de este dispositivo?',confirmReset:'BORRAR',cancel:'CANCELAR',cosmetic:'Cada personaje tiene sus propios poderes. Desbloquealos sobreviviendo en una carrera.',choose:'LISTO',local:'Récords de este dispositivo. Sin cuenta.',beat:'SUPERÁ TU RÉCORD',back:'VOLVER',lanes:'CAMBIÁ DE CARRIL',jump:'SALTÁ',slide:'DESLIZATE',goal:'Juntá 🧻 para bajar el Diaper Meter. Al 100%, todo termina. Un golpe acerca la prensa. Otro golpe cuando está cerca: te atrapan.',practice:'PRACTICÁ EN LA PISTA',saveImage:'GUARDAR IMAGEN ↓'},en:{run:'TAP TO RUN',characters:'CHARACTERS',records:'RECORDS',achievements:'ACHIEVEMENTS',donate:'SUPPORT',how:'HOW TO PLAY',distance:'DISTANCE',paused:'PAUSED',safe:'Your run is safe. For now.',resume:'▶ RESUME RUN',restart:'↻ RESTART',settings:'SETTINGS',menu:'⌂ MAIN MENU',bestCombo:'BEST COMBO',record:'BEST',share:'↗ SHARE',music:'MUSIC',voice:'VOICE',mute:'MUTE ALL',reduced:'REDUCED MOTION',haptics:'VIBRATION',language:'LANGUAGE',reset:'RESET PROGRESS',resetConfirm:'Clear records, paper and achievements from this device?',confirmReset:'CLEAR',cancel:'CANCEL',cosmetic:'Each character has signature powers. Unlock them by surviving one run.',choose:'READY',local:'Personal records on this device. No account.',beat:'BEAT YOUR BEST',back:'BACK',lanes:'CHANGE LANES',jump:'JUMP',slide:'SLIDE',goal:'Collect 🧻 to lower the Diaper Meter. At 100%, it’s over. One hit brings the press closer. Another hit while close: caught.',practice:'PRACTICE ON THE ROAD',saveImage:'SAVE IMAGE ↓'}};
function save(){if(previewCharacter||testCharacterMode)return;writeSave({progress:engine.progress,prefs});}
function tr(){document.documentElement.lang=prefs.language;for(const el of all('[data-i18n]'))el.textContent=I18N[prefs.language][el.dataset.i18n]||el.textContent;game.classList.toggle('reduced-motion',!prefs.motion);}
function text(id,value){if(lastHud[id]===value)return;lastHud[id]=value;$(id).textContent=value;}
function format(n){return Math.floor(n).toLocaleString(prefs.language==='es'?'es-AR':'en-US');}
function show(name){screen=name;for(const el of all('.screen'))el.hidden=el.id!==name;game.dataset.state=engine.state;const live=['run','cinematic','paused','settings','help'].includes(name)&&![STATES.MENU,STATES.OVER,STATES.RECORD,STATES.BOOT].includes(engine.state);$('#hud').hidden=name==='cinematic'||!live;$('#countdown').hidden=engine.state!==STATES.COUNTDOWN;}
function notify(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2100);}
function callout(message,extra=''){clearTimeout(calloutTimer);const el=$('#callout');el.replaceChildren();el.append(document.createTextNode(message));if(extra){const em=document.createElement('em');em.textContent=extra;el.append(em);}el.classList.remove('punch');void el.offsetWidth;el.classList.add('punch');calloutTimer=setTimeout(()=>el.classList.remove('punch'),1000);}
function haptic(pattern){if(prefs.haptics&&!prefs.mute)navigator.vibrate?.(pattern);}
function records(){const p=engine.progress;$('#total-tp').textContent=format(p.totalTP);$('#menu-best').textContent=format(p.bestDistance)+' m';$('#records-list').replaceChildren();for(const [label,value]of [['SCORE',p.bestScore],['DISTANCIA',format(p.bestDistance)+' m'],['MEJOR COMBO','×'+p.bestCombo],['TOTAL 🧻',p.totalTP],['CARRERAS',p.runs]]){const row=document.createElement('div'),l=document.createElement('span'),b=document.createElement('b');l.textContent=label;b.textContent=typeof value==='number'?format(value):value;row.append(l,b);$('#records-list').append(row);}const achievements=[['🏁','PRIMER ESCAPE','Terminá una carrera',p.runs>=1],['🛣','NO ME ALCANZA','Llegá a 500 m',p.bestDistance>=500],['🧻','PAPELITO','Juntá 50 rollos en total',p.totalTP>=50],['🔥','IMPARABLE','Alcanzá un combo ×6',p.bestCombo>=6],['🚀','LARGO CAMINO','Llegá a 2.000 m',p.bestDistance>=2000],['♛','OTRA VEZ','Terminá 10 carreras',p.runs>=10]];$('#achievement-list').replaceChildren();for(const [icon,title,detail,unlocked]of achievements){const row=document.createElement('div'),a=document.createElement('span'),b=document.createElement('div'),strong=document.createElement('b'),small=document.createElement('small');row.className=unlocked?'unlocked':'';a.textContent=unlocked?icon:'🔒';strong.textContent=title;small.textContent=detail;b.append(strong,small);row.append(a,b);$('#achievement-list').append(row);}}
function settingsUI(){for(const id of ['music','sfx','voice']){$('#'+id).value=prefs[id];$('#'+id+'-output').value=Math.round(prefs[id]*100)+'%';}$('#mute').checked=prefs.mute;$('#reduced').checked=!prefs.motion;$('#haptics').checked=prefs.haptics;$('#language').value=prefs.language;$('#reset-confirm').hidden=true;}
let selecting=false,starting=false;
function characters(){selector.render();difficultyUI();}
function difficultyUI(){for(const b of all('[data-difficulty]'))b.setAttribute('aria-pressed',b.dataset.difficulty===prefs.difficulty);}
for(const b of all('[data-difficulty]'))b.addEventListener('click',()=>{prefs.difficulty=b.dataset.difficulty;difficultyUI();save();});
difficultyUI();
const selector=new CharacterSelector($('#characters'),{progress:engine.progress,prefs,onPlay:async index=>{await chooseCharacter(index);if(prefs.character!==index)return;await run();}});
function characterPortraits(){const c=characterAt(prefs.character),src='../art/selector-'+c.id+'-portrait-v1.webp';for(const image of all('#meter-face,.pause-hero')){image.src=src;image.alt=c.short;}game.dataset.character=c.id;}
async function selectedArt(){characterPortraits();const c=characterAt(prefs.character);await Promise.all([...c.intro,c.result,c.portrait].filter(id=>!assets[id]).map(load));}
async function chooseCharacter(index){if(selecting||!isUnlocked(engine.progress,index))return;selecting=true;const prior=prefs.character;characters();try{await renderer.selectCharacter(index);engine.characterIndex=index;await selectedArt();save();}catch(e){notify('No se pudo cargar el personaje. Volvé a intentar.');await renderer.selectCharacter(prior);engine.characterIndex=prior;}finally{selecting=false;characters();}}

function modal(name){if([STATES.INTRO,STATES.REPEAT,STATES.RESTART].includes(engine.state))return;if([STATES.RUNNING,STATES.COUNTDOWN].includes(engine.state))engine.pause();dialogReturn=screen==='run'?'paused':screen;settingsUI();if(name==='characters'){selector.open();difficultyUI();}if(name==='leaderboard'||name==='achievements')records();show(name);}
function back(){show(dialogReturn);}
async function run(){if(dead||selecting||starting)return;starting=true;try{await audio.unlock();const audioReady=audio.decodeOptional();await Promise.all([renderer.prepareGameplay(),introReady,audioReady,selectedArt()]);engine.characterIndex=prefs.character;introShot=-1;lastBand=-1;lastHud={};clearTimeout(calloutTimer);$('#callout').classList.remove('punch');$('#intro-meter').hidden=true;$('#cinematic').classList.remove('handoff');$('#cinematic').style.removeProperty('opacity');$('#cinematic').removeAttribute('data-shot');renderer.shake=0;for(const p of renderer.particles)p.active=false;engine.difficulty=prefs.difficulty;engine.start({restart:false});$('#cinematic').style.pointerEvents='none';show('cinematic');$('#world').focus({preventScroll:true});}catch(error){notify('No se pudo iniciar. Volvé a intentar.');console.error(error);}finally{starting=false;}}
function onEvent(e){broadcast.event(e);if(e.type==='save')save();if(e.type==='pause'){pointer=null;accumulator=0;lastTime=0;audio.pause();show('paused');return;}if(e.type==='resume'){pointer=null;accumulator=0;lastTime=0;audio.resume(engine);show([STATES.INTRO,STATES.REPEAT].includes(engine.state)?'cinematic':'run');return;}if(e.type==='menu'){renderer?.event(e);audio.stopLoops();audio.stopStreamLoop(.3);audio.stopExternal();audio.setMode('menu');void audio.unlock();records();show('menu');return;}audio.event(e);renderer?.event(e);
 if(e.type==='go'){audio.setMode('running');show('run');$('#world').focus({preventScroll:true});if(e.resumed)callout('¡GO!');else if(engine.state===STATES.RUNNING)callout('¡CORRÉ!');}
 if(e.type==='near'){callout(prefs.language==='es'?'¡POR POCO!':'NEAR MISS!','+'+75*engine.combo);haptic(9);}
 if(e.type==='tp')haptic(5);
 if(e.type==='stumble'){callout(prefs.language==='es'?'¡CUIDADO!':'STUMBLE!','DIAPER METER +'+(e.penalty||engine.tuning.hit)+'%');haptic(35);}
 if(e.type==='power'){callout(POWERS.find(p=>p.id===e.id).name);haptic([10,25,20]);}
 if(e.type==='destroy')callout(POWERS.find(p=>p.id===e.power)?.name||'¡AFUERA!','+'+e.points);
 if(e.type==='powerEnd'&&e.id==='dollars'&&e.payout)callout('💵 +'+format(e.payout));
 if(e.type==='rescueWarning')callout(e.seconds+'…',prefs.language==='es'?'ATERRIZAJE':'LANDING');
 if(e.type==='relief'){callout('¡SALVADO!','+1000');haptic([15,20,15]);}
 if(e.type==='fail'){show('run');haptic([35,30,55]);}
 if(e.type==='end'){records();$('#failure-reason').textContent=engine.failReason==='press'?'LA PRENSA TE ATRAPÓ 📸':engine.failReason==='meter'?'DIAPER METER: 100%':engine.failReason==='bus'||engine.failReason==='vehicle'?'COLECTIVO: 1 · DIGNIDAD: 0':'LA CALLE NO PERDONA';const c=characterAt(prefs.character);$('.results-art').style.backgroundImage='url(../art/'+c.result+'.webp)';$('#quote').textContent=c.index?c.quote:engine.quote;$('#result-distance').textContent=format(engine.distance)+' m';$('#result-tp').textContent=format(engine.tp);$('#result-combo').textContent='×'+engine.bestCombo;$('#result-score').textContent=format(engine.score);$('#result-best').textContent=format(engine.progress.bestScore);$('#new-record').hidden=!engine.newRecord;show('results');if(engine.unlockedThisRun.length)showUnlocks([...engine.unlockedThisRun]);}
}
function showUnlocks(ids){if(!ids.length)return;const c=CHARACTERS.find(c=>c.id===ids.shift()),overlay=document.createElement('section');overlay.className='unlock-reveal';overlay.setAttribute('aria-label','Personaje desbloqueado');const heading=document.createElement('h2');heading.textContent='¡DESBLOQUEADO!';const image=new Image();image.src='../art/'+c.portrait+'.webp';image.alt=c.name;const title=document.createElement('h3');title.textContent=c.name;const detail=document.createElement('p');detail.textContent=c.unlock+' s · '+c.powers.map(id=>POWERS.find(p=>p.id===id).name).join(' · ');const button=document.createElement('button');button.className='primary';button.textContent='TOCÁ PARA CONTINUAR';button.onclick=()=>{overlay.remove();showUnlocks(ids);};overlay.append(heading,image,title,detail,button);game.append(overlay);}
function updateHUD(){text('#distance',format(engine.distance)+' m');text('#tp',format(engine.tp));text('#dollars',format(engine.dollars));text('#combo','×'+engine.combo*(engine.power==='dollars'?2:1));text('#meter-value',Math.floor(engine.meter)+'%');$('#meter-fill').style.width=engine.meter+'%';const band=meterBand(engine.meter),colors=['#8cf347','#ffdf49','#ff9929','#ff4b3f','#ff3159'];if(band!==lastBand){lastBand=band;game.style.setProperty('--meter-color',colors[band]);$('#meter-fill').style.background='linear-gradient(#fff4a2,'+colors[band]+')';$('#meter-status').textContent=(prefs.language==='es'?['TRANQUI','CUIDADO','URGENTE','NO NO NO','CRÍTICO']:['ALL GOOD','CAREFUL','URGENT','NO NO NO','CRITICAL'])[band];}$('#power-hud').hidden=!engine.power;if(engine.power){const p=POWERS.find(p=>p.id===engine.power);if($('#power-name').textContent!==p.name){$('#power-name').textContent=p.name;$('#power-icon').src='../art/'+POWER_ICONS[p.id];game.style.setProperty('--power-color',p.color);}text('#power-time','0:'+String(Math.ceil(engine.powerTime)).padStart(2,'0'));$('#power-progress').value=engine.powerTime/p.duration;}}
function intro(){const t=engine.introTime;const shot=t<1.9?0:t<3.7?1:t<5.5?2:t<6.94?3:4;if(shot!==introShot){introShot=shot;const stage=$('#intro-stage'),character=$('#intro-character');$('#cinematic').dataset.shot=shot;stage.style.opacity='0';const c=characterAt(prefs.character);$('#cinematic').dataset.character=c.id;stage.src='../art/'+(c.index?c.intro[shot]:shot===0?'opening-crowd':shot===4?'media-chase':'stage')+'.webp';character.hidden=c.index>0||shot===0||shot===4;if(!character.hidden){character.style.opacity='0';character.src='../art/'+['','speech','realization','escape',''][shot]+'.webp';requestAnimationFrame(()=>character.style.opacity='1');}requestAnimationFrame(()=>stage.style.opacity='1');$('#intro-meter').hidden=true;$('#intro-caption').textContent=c.captions[shot];audio.introCue(shot);}$('#hud').hidden=true;if(t>=8.2)$('#cinematic').classList.add('handoff');}
function resetProgress(){Object.assign(engine.progress,{bestScore:0,bestDistance:0,bestCombo:0,totalTP:0,runs:0,fullIntro:false,bestSurvival:0,unlocked:{milei:true}});chooseCharacter(0);save();records();$('#reset-confirm').hidden=true;notify(prefs.language==='es'?'Progreso borrado.':'Progress cleared.');}
async function prepareShare(){const version=++shareVersion;dialogReturn='results';show('share');$('#share-note').textContent=prefs.language==='es'?'Preparando tu tarjeta…':'Preparing your card…';$('#share-image').removeAttribute('src');$('#download').removeAttribute('href');try{const cdef=characterAt(prefs.character);if(!assets[cdef.result])await load(cdef.result);await document.fonts.ready;const c=document.createElement('canvas');c.width=720;c.height=1280;const g=c.getContext('2d');g.fillStyle='#07172e';g.fillRect(0,0,720,1280);if(assets[cdef.result])g.drawImage(assets[cdef.result],0,130,720,720);const grad=g.createLinearGradient(0,600,0,1280);grad.addColorStop(0,'#07172e00');grad.addColorStop(.4,'#07172e');g.fillStyle=grad;g.fillRect(0,600,720,680);g.textAlign='center';g.font='58px Diaper';g.fillStyle='#ffe14b';g.strokeStyle='#06203b';g.lineWidth=9;g.strokeText(cdef.short,360,95);g.fillText(cdef.short,360,95);g.fillStyle='#fff7e4';g.font='23px Diaper';g.fillText('DIAPER RUN · ¡AFUERA! EDITION',360,140);g.font='90px Diaper';g.fillStyle='#ffe24e';g.fillText(format(engine.distance)+' m',360,850);g.fillStyle='#fff6df';g.font='30px Diaper';g.fillText('🧻 '+engine.tp+'     COMBO ×'+engine.bestCombo,360,915);g.font='24px Diaper';g.fillStyle='#93d4f3';g.fillText('SCORE '+format(engine.score),360,974);if(engine.newRecord){g.font='31px Diaper';g.fillStyle='#ffd948';g.fillText('♛ NUEVO RÉCORD',360,1035);}g.font='20px Diaper';g.fillStyle='#fff4df';const quote=cdef.index?cdef.quote:engine.quote;const words=quote.split(' ');let line='',y=1090;for(const w of words){if(g.measureText(line+w).width>630){g.fillText(line,360,y);y+=27;line='';}line+=w+' ';}g.fillText(line,360,y);if(business){g.fillStyle='#8ccbf0';g.font='18px Arial';g.fillText('UGC GAMES · '+[business,locationName].filter(Boolean).join(' · '),360,1196,650);}g.strokeStyle='#62bbec';g.lineWidth=3;g.strokeRect(16,16,688,1248);const blob=await new Promise(resolve=>c.toBlob(resolve,'image/png'));if(!blob)throw Error('No image');if(version!==shareVersion)return;disposeShare();shareBlob=blob;shareUrl=URL.createObjectURL(blob);$('#share-image').src=shareUrl;$('#download').href=shareUrl;$('#share-note').textContent=prefs.language==='es'?'Compartí con tu app favorita o guardá la imagen.':'Share with your favorite app or save the image.';}catch{$('#share-note').textContent='No se pudo crear la tarjeta. Volvé e intentá de nuevo.';}}
function disposeShare(){if(shareUrl)URL.revokeObjectURL(shareUrl);shareUrl='';shareBlob=null;}
async function nativeShare(){if(!shareBlob)return;const file=new File([shareBlob],'diaper-run-result.png',{type:'image/png'});try{if(navigator.canShare?.({files:[file]})&&navigator.share){await navigator.share({files:[file],title:'El León se Cagó — Diaper Run',text:format(engine.distance)+' m · 🧻 '+engine.tp+' · Combo ×'+engine.bestCombo});}else if(navigator.share){await navigator.share({title:'Diaper Run',text:format(engine.distance)+' m · 🧻 '+engine.tp,url:shareLink});}else $('#download').click();}catch(e){if(e.name!=='AbortError'){$('#download').click();$('#share-note').textContent='Guardá la imagen y compartila desde tu app.';}}}
for(const el of all('[data-action]'))el.addEventListener('click',async()=>{audio.unlock();audio.event({type:'ui'});const a=el.dataset.action;if(a==='run')run();else if(a==='restart')run();else if(a==='resume')engine.resume();else if(a==='menu'){disposeShare();engine.menu();}else if(a==='exit'){engine.menu();audio.pause();if(parent!==window)parent.postMessage({type:'GAME_EXIT'},location.origin);}else if(['settings','characters','leaderboard','achievements','donate','help','disclaimer'].includes(a))modal(a);else if(a==='back')back();else if(a==='skip-intro')engine.skipIntro();else if(a==='share')prepareShare();else if(a==='native-share')nativeShare();else if(a==='reset')$('#reset-confirm').hidden=false;else if(a==='cancel-reset')$('#reset-confirm').hidden=true;else if(a==='confirm-reset')resetProgress();else if(a==='copy-alias'){try{await navigator.clipboard.writeText('Daiske.mp');$('#donation-note').textContent='Alias copiado. Abrí Mercado Pago y transferí a Daiske.mp.';}catch{$('#donation-note').textContent='Alias: Daiske.mp — copialo en tu app de Mercado Pago.';}}});
for(const id of ['music','sfx','voice'])$('#'+id).addEventListener('input',e=>{prefs[id]=Number(e.target.value);$('#'+id+'-output').value=Math.round(prefs[id]*100)+'%';audio.apply();save();});
for(const id of ['mute','reduced','haptics'])$('#'+id).addEventListener('change',e=>{prefs[id==='reduced'?'motion':id]=id==='reduced'?!e.target.checked:e.target.checked;audio.apply();tr();save();});
$('#language').addEventListener('change',e=>{prefs.language=e.target.value;tr();lastHud={};lastBand=-1;save();});

for(const b of all('[data-amount]'))b.addEventListener('click',()=>{for(const other of all('[data-amount]'))other.setAttribute('aria-pressed',other===b);$('#other-amount').value=b.dataset.amount;$('#donation-note').textContent='$'+format(Number(b.dataset.amount))+' ARS · Alias Daiske.mp. No se hizo ningún cobro.';});
$('#pause').addEventListener('click',()=>engine.pause());
const keys={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',ArrowUp:'jump',w:'jump',W:'jump',' ':'jump',ArrowDown:'slide',s:'slide',S:'slide'};
function keydown(e){if(/^(INPUT|SELECT|TEXTAREA)$/.test(e.target.tagName))return;if(e.key==='Escape'||e.key==='p'||e.key==='P'){if(engine.state===STATES.PAUSED&&screen==='paused')engine.resume();else engine.pause();e.preventDefault();return;}if(keys[e.key]&&[STATES.RUNNING].includes(engine.state)){e.preventDefault();if(!e.repeat)engine.input(keys[e.key]);}}
window.addEventListener('keydown',keydown);let pointer=null;
$('#world').addEventListener('pointerdown',e=>{if(![STATES.RUNNING].includes(engine.state))return;e.preventDefault();pointer={id:e.pointerId,x:e.clientX,y:e.clientY,used:false};$('#world').setPointerCapture(e.pointerId);});
$('#world').addEventListener('pointermove',e=>{if(!pointer||e.pointerId!==pointer.id||pointer.used)return;e.preventDefault();const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y,threshold=Math.max(18,Math.min(30,innerWidth*.055));if(Math.max(Math.abs(dx),Math.abs(dy))<threshold)return;engine.input(Math.abs(dx)>Math.abs(dy)?dx<0?'left':'right':dy<0?'jump':'slide');pointer.used=true;});
for(const name of ['pointerup','pointercancel','lostpointercapture'])$('#world').addEventListener(name,e=>{if(pointer?.id===e.pointerId)pointer=null;});
function pauseHidden(){pointer=null;accumulator=0;lastTime=0;engine.pause();audio.pause();}
document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseHidden();});window.addEventListener('blur',()=>{if([STATES.RUNNING,STATES.INTRO,STATES.REPEAT,STATES.COUNTDOWN].includes(engine.state))pauseHidden();});
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.type==='DIAPER_RUN_PAUSE')engine.pause();if(e.data?.type==='MENUTAP_GAME_CONTEXT'){business=String(e.data.businessName||'').slice(0,60);locationName=String(e.data.locationName||'').slice(0,70);shareLink=String(e.data.shareUrl||location.href);$('.brand-pill').textContent=business?business.toUpperCase():'UGC GAMES';}});
let accumulator=0;const FIXED_STEP=1/60;let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>renderer?.resize(),80);});
$('#world').addEventListener('runner-context-lost',()=>{engine.pause();notify('La pista se pausó. Recuperando gráficos…');});$('#world').addEventListener('runner-context-restored',()=>notify('Gráficos recuperados. Tocá seguir.'));
function loop(t){if(dead)return;if(window.DiaperDebug?.freezeFixture){lastTime=t;raf=requestAnimationFrame(loop);return;}const raw=lastTime?(t-lastTime)/1000:0;lastTime=t;const dt=Math.min(.1,raw);const before=engine.state;accumulator+=dt;let ticks=0;while(accumulator>=FIXED_STEP&&ticks++<6){engine.update(FIXED_STEP);accumulator-=FIXED_STEP;}if(ticks>=6)accumulator=0;if(before!==engine.state)game.dataset.state=engine.state;
 const active=[STATES.RUNNING,STATES.INTRO,STATES.REPEAT,STATES.COUNTDOWN,STATES.RESTART,STATES.IMPACT].includes(engine.state);if(active||engine.state===STATES.MENU)renderer.draw(engine,engine.state===STATES.COUNTDOWN?0:dt,accumulator/FIXED_STEP);if(engine.state===STATES.INTRO||engine.state===STATES.REPEAT)intro();if(engine.state===STATES.COUNTDOWN){$('#countdown').hidden=false;const label=String(Math.max(1,Math.ceil(engine.countTime/.5)));if(label!==countLast){countLast=label;$('#countdown').textContent=label;audio.event({type:'go'});}}else{$('#countdown').hidden=true;countLast='';}
 uiTime+=dt;if(active&&uiTime>.06){uiTime=0;updateHUD();}broadcast.update(engine,dt*engine.presentationScale);audio.tick(engine);if(raw>0&&active){frameSamples.push(raw*1000);if(frameSamples.length>300)frameSamples.shift();}if(!renderer.lowQuality&&frameSamples.length===300&&frameSamples.filter(v=>v>28).length>90){renderer.lowQuality=true;renderer.resize();}raf=requestAnimationFrame(loop);}
function cleanup(){dead=true;cancelAnimationFrame(raf);clearTimeout(toastTimer);clearTimeout(calloutTimer);clearTimeout(resizeTimer);audio.dispose();renderer?.dispose();disposeShare();}
window.addEventListener('pagehide',e=>{if(e.persisted)pauseHidden();else cleanup();});
window.addEventListener('pageshow',e=>{if(e.persisted){lastTime=0;notify('Pausado. Tocá continuar.');}});
tr();settingsUI();audio.loadOptional();
const loadingBar=$('#loading-bar');let loaded=0,fontReady=false,loaderArtReady=false,rendererReady=false,gameplayReady=false;function updateLoading(ready=false){const progress=Math.min(97,Math.round(loaded/8*20+(fontReady?5:0)+(loaderArtReady?2:0)+(rendererReady?48:0)+(gameplayReady?25:0)));const percent=ready?100:progress;loadingBar.setAttribute('aria-valuenow',percent);loadingBar.style.setProperty('--load-progress',percent+'%');$('#loading-percent').textContent=percent+'%';if(ready){$('#boot-status').textContent='¡LISTO!';$('#boot').classList.add('boot-ready');}}
async function load(id){try{const i=new Image();i.src='../art/'+id+'.webp';await i.decode();assets[id]=i;}catch(e){loadErrors.push(id);}finally{loaded++;updateLoading();}}
const introReady=Promise.all(['opening-crowd','media-chase','stage','speech','realization','panic','rage','escape'].map(load));

try{const fonts=document.fonts.ready.then(()=>{fontReady=true;updateLoading();});const loaderImage=Promise.all([...$('#boot').querySelectorAll('img')].map(image=>image.decode().catch(()=>{}))).then(()=>{loaderArtReady=true;updateLoading();});renderer=new RunnerRenderer($('#world'),prefs,assets);const base=renderer.ready.then(()=>{rendererReady=true;updateLoading();});const gameAssets=renderer.prepareGameplay().then(()=>{gameplayReady=true;updateLoading();});await Promise.all([fonts,loaderImage,base,gameAssets,introReady,selectedArt(),coverReady]);const minBoot=Math.max(0,720-(performance.now()-bootStarted));if(minBoot)await new Promise(resolve=>setTimeout(resolve,minBoot));updateLoading(true);await new Promise(resolve=>requestAnimationFrame(resolve));renderer.draw(engine,0);introShot=-1;lastBand=-1;lastHud={};$('#intro-meter').hidden=true;$('#cinematic').classList.remove('handoff');$('#cinematic').style.removeProperty('opacity');$('#cinematic').removeAttribute('data-shot');renderer.shake=0;for(const p of renderer.particles)p.active=false;if(testCharacterMode){engine.state=STATES.MENU;engine.emit('menu');renderer.draw(engine,0);show('menu');if(query.has('selector'))modal('characters');raf=requestAnimationFrame(loop);}else{engine.start();$('#cinematic').style.pointerEvents='none';show('cinematic');raf=requestAnimationFrame(loop);}parent.postMessage({type:'GAME_READY'},location.origin);
 if(new URLSearchParams(location.search).get('test')==='1')window.DiaperDebug={engine,renderer,audio,prefs,assets,ready:()=>introReady,start:()=>{engine.reset();engine.state=STATES.RUNNING;engine.emit('start');engine.emit('go');show('run');},advance:s=>{for(let t=0;t<s;t+=1/60)engine.update(Math.min(1/60,s-t));updateHUD();renderer.draw(engine,0);},input:a=>engine.input(a),activate:id=>engine.activate(id),spawn:(...args)=>engine.spawn(...args),snapshot:()=>({...engine.snapshot(),screen,loadErrors,render:renderer.snapshot(),audio:audio.snapshot(),broadcast:broadcast.snapshot(),frameP95:[...frameSamples].sort((a,b)=>a-b)[Math.floor(frameSamples.length*.95)]||0,fps:1000/(frameSamples.reduce((a,b)=>a+b,0)/(frameSamples.length||1))}),save,run,share:prepareShare};
 if(window.DiaperDebug){const {installAcceptanceControls}=await import('./acceptance-controls.js');installAcceptanceControls(window.DiaperDebug);}
}catch(e){console.error(e);$('#boot-status').textContent='NO PUDIMOS CARGAR LA PISTA. RECARGÁ PARA REINTENTAR.';$('#boot').dataset.error=e.message;}
