import * as T from './vendor/three.module.min.js';
import {GLTFLoader} from './vendor/loaders/GLTFLoader.js';
import {buildSegment,buildPalace,buildProp,buildPower,buildHelicopter,bake,material,PALETTE,installArt,flagClock,installPropArt,installHygieneArt,HYGIENE,installStreetArt,STREET_ART,contactShadowMaterial,PRESS_OBSTACLES,installPressObstacleArt} from './models.js';
import {STATES} from './engine.js';
import {PressActors} from './press-actors.js';
import {RunnerEffects} from './effects.js';
import {HERO_HEIGHT,shape} from './track.js';
export class RunnerRenderer{
 constructor(canvas,prefs,assets){this.canvas=canvas;this.prefs=prefs;this.assets=assets;this.shake=0;this.particles=Array.from({length:100},()=>({active:false}));this.clock=0;this.phase=0;this.distance=0;this.lastPower='';this.stats={};this.modelReady=false;this.error=null;
  this.gl=new T.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.gl.outputColorSpace=T.SRGBColorSpace;this.gl.toneMapping=T.ACESFilmicToneMapping;this.gl.toneMappingExposure=1.12;
  this.scene=new T.Scene();const sky=document.createElement('canvas');sky.width=2;sky.height=256;const sky2d=sky.getContext('2d'),skyGradient=sky2d.createLinearGradient(0,0,0,256);skyGradient.addColorStop(0,'#207fd5');skyGradient.addColorStop(.6,'#87d0ec');skyGradient.addColorStop(1,'#c0e6ec');sky2d.fillStyle=skyGradient;sky2d.fillRect(0,0,2,256);const skyTexture=new T.CanvasTexture(sky);skyTexture.colorSpace=T.SRGBColorSpace;this.scene.background=skyTexture;this.scene.fog=new T.Fog(0xadd8e6,65,170);this.camera=new T.PerspectiveCamera(62,1,.1,260);
  this.scene.add(new T.HemisphereLight(0xd1ecff,0x8f8064,1.5));const sun=new T.DirectionalLight(0xffefd0,2.6);sun.position.set(-15,28,12);this.scene.add(sun);
  this.holes=Array.from({length:8},()=>new T.Vector4(0,0,0,0));
  const clouds=new T.Group(),cloudMaterial=new T.MeshBasicMaterial({color:0xe8f6fa});for(const [x,y,z,size]of[[-40,29,-130,7],[38,34,-160,10],[2,36,-200,9]])for(let j=0;j<5;j++){const puff=new T.Mesh(new T.SphereGeometry(1,10,6),cloudMaterial);puff.position.set(x+j*size*.8,y+Math.sin(j*1.7)*size*.2,z);puff.scale.set(size,size*.4,size*.65);clouds.add(puff);}for(const part of bake(clouds))this.scene.add(new T.Mesh(part.geometry,material(0xe8f6fa,{emissive:0xe8f6fa,emissiveIntensity:.8,fog:false})));
  this.world=new T.Group();this.scene.add(this.world);this.segments=[];for(let variant=0;variant<4;variant++){const source=buildSegment(variant),parts=bake(source);for(const part of parts){if(part.material.color.getHex()===PALETTE.road){part.material.onBeforeCompile=shader=>{shader.uniforms.trackHoles={value:this.holes};shader.vertexShader='varying vec3 roadWorld;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <worldpos_vertex>','#include <worldpos_vertex>\nroadWorld=(modelMatrix*instanceMatrix*vec4(transformed,1.0)).xyz;');shader.fragmentShader='varying vec3 roadWorld; uniform vec4 trackHoles[8];\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <clipping_planes_fragment>','#include <clipping_planes_fragment>\nfor(int h=0;h<8;h++){vec4 gap=trackHoles[h];if(gap.w>0.5&&abs(roadWorld.x-gap.x)<gap.w&&roadWorld.z<gap.y&&roadWorld.z>gap.z)discard;}');};}
const inst=new T.InstancedMesh(part.geometry,part.material,2);inst.frustumCulled=false;inst.name='street-'+variant;this.world.add(inst);this.segments.push({inst,variant});}source.clear();}
  this.palace=new T.Group();for(const part of bake(buildPalace())){const m=part.material.clone();m.fog=false;this.palace.add(new T.Mesh(part.geometry,m));}this.scene.add(this.palace);
  this.dynamic=new Map();for(const kind of [...HYGIENE,...PRESS_OBSTACLES,'dumpster','skip','falcon','donkey','pothole','bus','vehicle','low','block','high','cone','trash','gap','ramp','roof','tp','dollar',...['magnet','lion','afuera','dollars','rescue'].map(id=>'power-'+id)]){
   const source=kind.startsWith('power-')?buildPower(kind.slice(6)):buildProp(kind);const parts=bake(source);const list=parts.map(({geometry,material})=>{const i=new T.InstancedMesh(geometry,material,180);i.count=0;i.frustumCulled=false;i.instanceMatrix.setUsage(T.DynamicDrawUsage);this.scene.add(i);return i;});this.dynamic.set(kind,list);
  }
  this.heroRoot=new T.Group();this.scene.add(this.heroRoot);this.hero=null;this.mixer=null;this.actions=new Map();this.activeAction='';this.headPose=new T.Quaternion();this.headPoseApplied=false;this.heroRoot.rotation.y=Math.PI;
  this.contactShadow=new T.Mesh(new T.CircleGeometry(.85,24),contactShadowMaterial.clone());this.contactShadow.rotation.x=-Math.PI/2;this.contactShadow.scale.set(1,.7,1);this.scene.add(this.contactShadow);
  this.chainsaw=buildPower('afuera');this.chainsaw.scale.setScalar(1.5);this.chainsaw.visible=false;this.heroRoot.add(this.chainsaw);this.chainsaw.position.set(-.9,1.25,.18);
  this.aura=new T.Mesh(new T.TorusGeometry(.8,.025,8,48),new T.MeshBasicMaterial({color:0xffbe32,transparent:true,opacity:.65,depthWrite:false}));this.aura.rotation.x=Math.PI/2;this.aura.visible=false;this.scene.add(this.aura);
  this.effects=new RunnerEffects(this);this.helicopter=new T.Group();this.helicopter.visible=false;this.scene.add(this.helicopter);this.rotor=this.helicopter.getObjectByName('rotor');
  this.dummy=new T.Object3D();this.particleMesh=new T.InstancedMesh(new T.BoxGeometry(.10,.10,.10),new T.MeshBasicMaterial({color:0xffda55}),100);this.particleMesh.count=0;this.particleMesh.frustumCulled=false;this.scene.add(this.particleMesh);
  this.canvas.addEventListener('webglcontextlost',this.contextLost=e=>{e.preventDefault();this.error='context';canvas.dispatchEvent(new CustomEvent('runner-context-lost'));});this.canvas.addEventListener('webglcontextrestored',this.contextRestored=()=>{this.error=null;this.resize();canvas.dispatchEvent(new CustomEvent('runner-context-restored'));});
  this.press=new PressActors(this);this.resize();this.characterReady=this.loadCharacter();this.ready=Promise.all([this.characterReady,this.loadRoad(),this.loadArt(),this.loadPropArt(),this.loadSkyline()]).then(async()=>{await this.gl.compileAsync(this.scene,this.camera);return this;});
 }
 prepareGameplay(){if(!this.gameplayReady)this.gameplayReady=Promise.allSettled([this.loadHelicopter(),this.loadHygiene(),this.loadPressObstacleArt(),this.loadStreetArt(),this.loadImpactHeads(),this.press.ensureLoaded()]);return this.gameplayReady;}
 async loadSkyline(){const tex=await new T.TextureLoader().loadAsync('../art/casa-rosada-premium.webp');tex.colorSpace=T.SRGBColorSpace;const m=new T.MeshBasicMaterial({map:tex,transparent:true,alphaTest:.15,depthWrite:false,toneMapped:false,fog:false,opacity:.93});const skyline=new T.Mesh(new T.PlaneGeometry(52,26),m);skyline.position.set(0,10.9,-179.9);this.scene.add(skyline);this.palace.visible=false;this.skylineReady=true;}
 async loadPropArt(){const loader=new T.TextureLoader();const textures=await Promise.all(['bus-surfaces-premium','hazard-surfaces-premium'].map(id=>loader.loadAsync('../art/'+id+'.webp')));for(const tex of textures){tex.colorSpace=T.SRGBColorSpace;tex.anisotropy=Math.min(4,this.gl.capabilities.getMaxAnisotropy());}installPropArt(...textures);this.propArtReady=true;}
 async loadArt(){const loader=new T.TextureLoader();const [foliage,surface]=await Promise.all(['foliage-premium','materials-premium'].map(id=>loader.loadAsync('../art/'+id+'.webp')));for(const tex of [foliage,surface]){tex.colorSpace=T.SRGBColorSpace;tex.anisotropy=Math.min(4,this.gl.capabilities.getMaxAnisotropy());}installArt(foliage,surface);const cloth=surface.clone();cloth.offset.set(.5,0);cloth.repeat.set(.5,.5);cloth.needsUpdate=true;await this.characterReady;if(this.hero)for(const m of this.jacketMaterials||[]){m.map=cloth;m.color.setHex(0xd7e3ef);m.needsUpdate=true;}const foldCanvas=document.createElement('canvas');foldCanvas.width=foldCanvas.height=128;const fold=foldCanvas.getContext('2d'),image=fold.createImageData(128,128);for(let y=0;y<128;y++)for(let x=0;x<128;x++){const i=(y*128+x)*4,v=128+Math.sin(y*.20+Math.sin(x*.10)*1.1)*17+Math.sin(x*1.8+y*1.6)*3;image.data[i]=image.data[i+1]=image.data[i+2]=v;image.data[i+3]=255;}fold.putImageData(image,0,0);const bump=new T.CanvasTexture(foldCanvas);bump.wrapS=bump.wrapT=T.RepeatWrapping;for(const m of this.jacketMaterials||[]){m.bumpMap=bump;m.bumpScale=.018;m.roughness=.72;m.needsUpdate=true;}this.clothReady=true;}
 async loadImpactHeads(){const loader=new T.TextureLoader();this.impactTextures=await Promise.all(['hit-face-v2','crash-face-v2'].map(id=>loader.loadAsync('../art/'+id+'.webp')));for(const t of this.impactTextures)t.colorSpace=T.SRGBColorSpace;await this.characterReady;this.effects.mountImpactHead(this.hero,this.impactTextures);}
 async loadPressObstacleArt(){const textures=await Promise.all(PRESS_OBSTACLES.map(k=>new T.TextureLoader().loadAsync('../art/press-'+k+'.webp')));for(const t of textures)t.colorSpace=T.SRGBColorSpace;installPressObstacleArt(textures);}
 async loadStreetArt(){const textures=await Promise.all(STREET_ART.map(k=>new T.TextureLoader().loadAsync('../art/'+k+'-v1.webp')));for(const t of textures)t.colorSpace=T.SRGBColorSpace;installStreetArt(textures);}
 async loadHygiene(){const loader=new T.TextureLoader();const textures=await Promise.all(HYGIENE.map(k=>loader.loadAsync('../art/'+k+'-v1.webp')));for(const t of textures)t.colorSpace=T.SRGBColorSpace;installHygieneArt(textures);this.hygieneReady=true;}
 async loadHelicopter(){const texture=await new T.TextureLoader().loadAsync('../art/helicopter-rear-body-v1.webp');texture.colorSpace=T.SRGBColorSpace;const body=new T.Mesh(new T.PlaneGeometry(2.6,2.6),new T.MeshBasicMaterial({name:'rear rescue body',map:texture,transparent:true,alphaTest:.012,alphaToCoverage:true,depthWrite:false,opacity:.97,toneMapped:true,color:0xe6f1fa,side:T.DoubleSide}));body.material.onBeforeCompile=s=>{s.uniforms.bodyTexel={value:new T.Vector2(.75/texture.image.width,.75/texture.image.height)};s.fragmentShader='uniform vec2 bodyTexel;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\nfloat edgeAlpha=(texture2D(map,vMapUv+vec2(bodyTexel.x,0.)).a+texture2D(map,vMapUv-vec2(bodyTexel.x,0.)).a+texture2D(map,vMapUv+vec2(0.,bodyTexel.y)).a+texture2D(map,vMapUv-vec2(0.,bodyTexel.y)).a)*.25;\ndiffuseColor.a*=smoothstep(.015,.38,edgeAlpha);');};body.position.y=.25;body.rotation.x=-.18;this.helicopterBody=body;this.helicopter.add(body);this.rotor=new T.Group();this.rotor.position.set(0,1.42,-.19);this.rotor.name='rotor';const mat=new T.MeshStandardMaterial({color:0x192a36,roughness:.5});for(const angle of[0,Math.PI/2]){const blade=new T.Mesh(new T.BoxGeometry(4.6,.025,.13),mat);blade.rotation.y=angle;this.rotor.add(blade);}this.helicopter.add(this.rotor);const tether=new T.Mesh(new T.CylinderGeometry(.022,.022,.95,8),mat);tether.position.set(0,-1.09,.1);this.helicopter.add(tether);this.helicopterSmoke=new T.Group();this.scene.add(this.helicopterSmoke);this.smokePuffs=Array.from({length:9},(_,i)=>{const puff=new T.Mesh(new T.SphereGeometry(.18,8,6),new T.MeshBasicMaterial({color:0xd1dce4,transparent:true,opacity:0,depthWrite:false}));this.helicopterSmoke.add(puff);return puff;});this.helicopterReady=true;}
 async loadRoad(){const texture=await new T.TextureLoader().loadAsync('../art/asphalt-v3.webp');texture.colorSpace=T.SRGBColorSpace;texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.anisotropy=Math.min(4,this.gl.capabilities.getMaxAnisotropy());const road=material(PALETTE.road);road.map=texture;road.color.setHex(0x9eb6c8);road.needsUpdate=true;for(const {inst}of this.segments)if(inst.material===road){const p=inst.geometry.attributes.position,uv=inst.geometry.attributes.uv;for(let i=0;i<p.count;i++)uv.setXY(i,p.getX(i)/6,p.getZ(i)/6);uv.needsUpdate=true;}}
 async loadCharacter(){this.loadCharacterPromise=new GLTFLoader().loadAsync('../models/milei-character.glb');const gltf=await this.loadCharacterPromise;this.hero=gltf.scene;this.hero.traverse(o=>{if(o.isMesh){o.frustumCulled=false;if(o.material){o.material.roughness=Math.max(.45,o.material.roughness);o.material.side=T.DoubleSide;}}});this.heroRoot.add(this.hero);this.hero.updateMatrixWorld(true);const bounds=new T.Box3().setFromObject(this.hero,true);this.sourceHeroHeight=bounds.max.y-bounds.min.y;if(!Number.isFinite(this.sourceHeroHeight)||this.sourceHeroHeight<=0)throw Error('Invalid character bounds');this.heroScale=HERO_HEIGHT/this.sourceHeroHeight;this.heroRoot.scale.setScalar(this.heroScale);this.mixer=new T.AnimationMixer(this.hero);for(const clip of gltf.animations){const a=this.mixer.clipAction(clip);this.actions.set(clip.name,a);a.play();a.enabled=true;a.setEffectiveWeight(0);}
  if(!this.actions.has('run')||!this.hero.getObjectByProperty('type','SkinnedMesh'))throw Error('Character rig or run clip missing');this.jacketMaterials=[];this.hero.traverse(o=>{if(o.isMesh)for(const m of Array.isArray(o.material)?o.material:[o.material])if(m.name==='midnight tailoring')this.jacketMaterials.push(m);});this.effects.bind(this.hero);this.heroRoot.updateMatrixWorld(true);this.restFootOffset=this.effects.floorY();const hand=this.effects.bones.hand_R;if(hand){hand.add(this.chainsaw);this.chainsaw.position.set(0,0,0);this.chainsaw.rotation.set(-.3,0,-.75);this.chainsaw.scale.setScalar(1.15);}this.modelReady=true;this.setAction('menu_idle',0);await this.gl.compileAsync(this.scene,this.camera);return this;
 }
 resize(){const r=this.canvas.getBoundingClientRect();this.w=r.width;this.h=r.height;const ratio=Math.min(this.lowQuality?1:1.5,devicePixelRatio||1);this.gl.setPixelRatio(ratio);this.gl.setSize(this.w,this.h,false);this.camera.aspect=this.w/this.h;this.camera.fov=this.w>this.h?64:54;this.camera.updateProjectionMatrix();}
 setAction(name,duration=.12){if(name===this.activeAction||!this.actions.has(name))return;const next=this.actions.get(name),prev=this.actions.get(this.activeAction);const stride=['run','lean_left','lean_right'];const phase=prev&&stride.includes(name)&&stride.includes(this.activeAction)?(prev.time/prev.getClip().duration)%1:0;next.reset();next.time=phase*next.getClip().duration;next.setEffectiveWeight(1).play();if(['fall','slide_enter','slide_exit','jump_takeoff','jump_land'].includes(name)){next.setLoop(T.LoopOnce,1);next.clampWhenFinished=true;}else{next.setLoop(T.LoopRepeat,Infinity);next.clampWhenFinished=false;}if(prev)prev.crossFadeTo(next,duration,false);this.activeAction=name;}
 burst(lane,count=12){for(let i=0;i<count;i++){const p=this.particles.find(p=>!p.active);if(!p)break;Object.assign(p,{active:true,x:lane*3.2,y:1.1,z:0,vx:(Math.random()-.5)*3,vy:1+Math.random()*3,vz:(Math.random()-.5)*3,life:.4+Math.random()*.3});}}
 event(e){this.effects.event(e);if(e.type==='tp'||e.type==='dollar')this.burst(e.lane,5);if(e.type==='destroy')this.burst(e.lane,18);if(e.type==='stumble'){this.stumble=.4;this.shake=.12;}if(e.type==='fail'){this.failed=true;this.failureClock=0;this.setAction('fall',.07);}if(e.type==='start'||e.type==='go'||e.type==='menu'){this.failed=false;if(e.type!=='go')this.heliPhase='idle';}if(e.type==='power'&&e.id==='afuera')this.burst(0,18);if(e.type==='land')this.landed=.16;}
 draw(e,dt=0,alpha=1){if(this.error)return;const frozen=e.state===STATES.PAUSED||e.state===STATES.COUNTDOWN;const menu=e.state===STATES.MENU||e.state===STATES.BOOT;const moving=[STATES.RUNNING].includes(e.state);const scaled=frozen?0:dt*(moving?e.presentationScale:1);this.clock+=scaled;flagClock.value=this.clock;
  // Reuse the last rendered sample throughout pause/countdown, not the ticking RAF remainder.
  if(frozen)alpha=this.lastAlpha??1;else this.lastAlpha=alpha;const mix=(a,b)=>a+(b-a)*alpha;const distance=menu?this.clock*2.5:mix(e.previousDistance??e.distance,e.distance);this.distance=distance;this.phase=distance%40;
  // Each segment keeps its identity as it passes. Recycling happens behind the
  // camera into fog, rather than replacing every facade at each 40 m boundary.
  const span=this.lowQuality?160:320;for(const {inst,variant}of this.segments){inst.count=this.lowQuality?1:2;for(let j=0;j<inst.count;j++){const index=variant+j*4;let z=distance%span-index*40;if(z>40)z-=span;this.dummy.position.set(0,0,z);this.dummy.rotation.set(0,0,0);this.dummy.scale.setScalar(1);this.dummy.updateMatrix();inst.setMatrixAt(j,this.dummy.matrix);}inst.instanceMatrix.needsUpdate=true;}
  let holeIndex=0;for(const h of this.holes)h.w=0;for(const o of e.pool.items)if(o.active&&['gap','manhole','trench'].includes(o.kind)&&holeIndex<8)this.holes[holeIndex++].set(o.lane*3.2,-mix(o.prevZ,o.z),-mix(o.prevZ,o.z)-shape(o.kind).length,shape(o.kind).width*.49);
  const counts=new Map();for(const [key,list]of this.dynamic){counts.set(key,0);for(const m of list)m.count=0;}
  for(const o of e.pool.items){if(!o.active||menu)continue;const key=o.kind==='power'?'power-'+o.power:o.kind;const list=this.dynamic.get(key);if(!list)continue;const n=counts.get(key);this.dummy.position.set(o.lane*3.2,o.y||0,-mix(o.prevZ,o.z));const pickup=['tp','dollar','power'].includes(o.kind);if(pickup){this.dummy.position.y+=.55+Math.sin(this.clock*3+o.id)*.07;this.dummy.rotation.set(0,o.kind==='tp'?this.clock*.7:this.clock*1.8,0);this.dummy.scale.setScalar(o.kind==='power'?1.45:o.kind==='tp'?1.12:1.08);}else{this.dummy.rotation.set(0,0,0);this.dummy.scale.setScalar(1);}this.dummy.updateMatrix();for(const m of list){m.setMatrixAt(n,this.dummy.matrix);if(key==='bus'){m.setColorAt(n,new T.Color([0xffffff,0xaddcec,0xe8b7ae,0xb6d9b7][o.id%4]));if(m.instanceColor)m.instanceColor.needsUpdate=true;}}counts.set(key,n+1);}
  for(const [key,list]of this.dynamic)for(const m of list){m.count=counts.get(key);m.instanceMatrix.needsUpdate=true;}
  const x=menu?0:mix(e.previousX??e.x,e.x)*3.2;const y=menu?0:mix(e.previousY??0,e.groundY+e.jumpY+e.airY);const ground=menu?0:mix(e.previousGroundY??e.groundY,e.groundY);this.heroRoot.position.set(x,y,0);this.heroRoot.rotation.y=menu?.22:Math.PI;const steer=menu?0:(e.lane-e.x);this.heroRoot.rotation.z=menu?0:-steer*.16;
  if(this.lastCharacter!==this.prefs.character||this.lastCloth!==this.clothReady){for(const m of this.jacketMaterials||[])m.color.setHex([this.clothReady?0xd7e3ef:0x09254b,0x9e79bb,0x7bb895][this.prefs.character]||0x09254b);this.lastCharacter=this.prefs.character;this.lastCloth=this.clothReady;}
  if(this.lastSlide>0&&e.slideTime<=0)this.slideExit=.15;this.lastSlide=e.slideTime;this.slideExit=Math.max(0,(this.slideExit||0)-scaled);
  if(this.mixer){let name=menu?'menu_idle':e.state===STATES.IMPACT||this.failed?'fall':this.stumble>0?'stumble':e.power==='rescue'?'rescue_hang':e.slideTime>0?(e.slideTime>.65?'slide_enter':'slide_hold'):e.jumpY>.03?(e.actionAge<.16?'jump_takeoff':'jump_air'):this.landed>0?'jump_land':this.slideExit>0?'slide_exit':Math.abs(steer)>.12?(steer<0?'lean_left':'lean_right'):'run';this.setAction(name,name.startsWith('slide')?.035:.12);const a=this.actions.get(name);if(a)a.setEffectiveTimeScale(['run','lean_left','lean_right'].includes(name)?Math.min(1.65,1.02+e.speed*.016):1);const head=this.effects.bones.head;if(head&&this.headPoseApplied)head.quaternion.copy(this.headPose);this.mixer.update(scaled);this.headPoseApplied=false;if(head&&this.failed){this.headPose.copy(head.quaternion);head.rotateX(-.55*Math.min(1,(this.failureClock||0)/.25));this.headPoseApplied=true;}this.heroRoot.updateMatrixWorld(true);let floor=this.effects.floorY(this.failed);if(this.failed)this.failureClock=(this.failureClock||0)+scaled;if(Number.isFinite(floor)){const airborne=!menu&&!this.failed&&(y>ground+.025||e.vy>0);this.heroRoot.position.y+=airborne?.035-(this.restFootOffset||0):y+.035-floor;this.heroRoot.updateMatrixWorld(true);}this.effects.update(e,scaled,x,this.heroRoot.position.y,menu);}
  this.stumble=Math.max(0,(this.stumble||0)-scaled);this.landed=Math.max(0,(this.landed||0)-scaled);this.shake=Math.max(0,this.shake-scaled);this.contactShadow.position.set(x,ground+.035,0);const shadowScale=Math.max(.5,1-(e.jumpY+e.airY)*.12);this.contactShadow.scale.set(shadowScale,shadowScale*.7,1);this.contactShadow.material.opacity=Math.max(.07,.25-(e.jumpY+e.airY)*.025);
  this.chainsaw.visible=e.power==='afuera';this.chainsaw.rotation.x=-.3+Math.sin(this.clock*38)*.018;this.aura.visible=false;
  this.updateHelicopter(e,scaled);
  let pc=0;for(const p of this.particles){if(!p.active)continue;p.life-=scaled;if(p.life<=0){p.active=false;continue;}p.x+=p.vx*scaled;p.y+=p.vy*scaled;p.vy-=6*scaled;p.z+=p.vz*scaled;this.dummy.position.set(p.x,p.y,p.z);this.dummy.rotation.set(this.clock*3,0,this.clock*2);this.dummy.scale.setScalar(Math.min(1,p.life*4));this.dummy.updateMatrix();this.particleMesh.setMatrixAt(pc++,this.dummy.matrix);}this.particleMesh.count=pc;this.particleMesh.instanceMatrix.needsUpdate=true;
  const lift=y*.80;const flight=Math.min(1,mix(e.previousAirY??e.airY,e.airY)/5);const cameraX=x*.88;this.camera.position.set(cameraX,3.2+lift+flight*.8,6.5+flight*1.4);if(this.prefs.motion&&this.shake>0)this.camera.position.x+=Math.sin(this.clock*65)*this.shake*.18;this.camera.lookAt(cameraX,.45+lift+flight*1.35,-8);this.press.update(e,scaled,x);this.press.renderFeed(scaled);this.heroRoot.visible=!['GAME_OVER','NEW_HIGH_SCORE'].includes(e.state);this.gl.render(this.scene,this.camera);
  this.stats={drawCalls:this.gl.info.render.calls,triangles:this.gl.info.render.triangles,geometries:this.gl.info.memory.geometries,textures:this.gl.info.memory.textures,clip:this.activeAction,modelReady:this.modelReady,heroHeight:HERO_HEIGHT,heroScale:this.heroScale,sourceHeroHeight:this.sourceHeroHeight,worldDistance:distance,segmentPhase:this.phase,footY:this.effects.floorY(),effects:this.effects.stats,helicopterReady:this.helicopterReady,press:this.press.snapshot()};
 }
 updateHelicopter(e,dt){
  const active=e.power==='rescue',hidden=['MENU','BOOT','INTRO','REPEAT_INTRO','GAME_OVER','NEW_HIGH_SCORE'].includes(e.state);
  if(hidden){this.heliPhase='idle';this.helicopter.visible=false;if(this.helicopterSmoke)this.helicopterSmoke.visible=false;return;}
  if(active&&this.heliPhase!=='hover'&&this.heliPhase!=='arrive'){this.heliPhase='arrive';this.heliTime=0;}
  if(!active&&['hover','arrive'].includes(this.heliPhase)){this.heliPhase='leave';this.heliTime=0;this.heliExit=this.helicopter.position.clone();}
  this.heliTime=(this.heliTime||0)+dt;
  const target=this.effects.handCenter(new T.Vector3()).add(new T.Vector3(0,1.55,0));
  this.helicopter.visible=['arrive','hover','leave'].includes(this.heliPhase);
  if(active){const t=Math.min(1,this.heliTime/.85),ease=t*t*(3-2*t);if(this.heliPhase==='arrive'){this.helicopter.position.copy(target).add(new T.Vector3((1-ease)*4,(1-ease)*2,-(1-ease)*7));if(t===1)this.heliPhase='hover';}else this.helicopter.position.lerp(target,1-Math.exp(-dt*12));this.helicopter.rotation.set(0,Math.sin(this.clock*1.8)*.025,Math.sin(this.clock*1.3)*.015);if(this.helicopterBody)this.helicopterBody.material.opacity=.97;}
  if(this.heliPhase==='leave'){const t=Math.min(1,this.heliTime/1.65),ease=t*t;this.helicopter.position.copy(this.heliExit).add(new T.Vector3(10*ease,8*ease,-26*ease));this.helicopter.rotation.set(-.10*t,-.35*t,-.22*Math.sin(t*Math.PI));if(this.helicopterBody)this.helicopterBody.material.opacity=.97*(1-Math.max(0,(t-.7)/.3));if(t===1)this.heliPhase='idle';}
  if(this.rotor&&this.helicopter.visible)this.rotor.rotation.y+=dt*42;
  if(this.helicopterSmoke){const leaving=this.heliPhase==='leave';this.helicopterSmoke.visible=leaving;for(let i=0;i<this.smokePuffs.length;i++){const puff=this.smokePuffs[i],age=this.heliTime-i*.07;puff.visible=leaving&&age>0&&age<1.2;if(puff.visible){puff.position.copy(this.heliExit).add(new T.Vector3(Math.sin(i*2)*age*.7,age*.8-.3,i*.15));puff.scale.setScalar(.6+age*2);puff.material.opacity=.28*Math.max(0,1-age/1.2);}}}
 }
 project(lane,z){const v=new T.Vector3(lane*3.2,0,-z).project(this.camera);return {x:(v.x+1)*this.w/2,y:(1-v.y)*this.h/2,s:1/(z+1)};}
 portrait(){return '../art/panic.webp';}
 snapshot(){return {...this.stats,quality:this.lowQuality?'low':'standard'};}
 dispose(){this.canvas.removeEventListener('webglcontextlost',this.contextLost);this.canvas.removeEventListener('webglcontextrestored',this.contextRestored);this.effects?.dispose();this.press?.dispose();const geos=new Set(),mats=new Set(),textures=new Set();this.scene.traverse(o=>{if(o.geometry)geos.add(o.geometry);if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material])mats.add(m);});for(const g of geos)g.dispose();for(const m of mats){for(const key of ['map','alphaMap','normalMap','roughnessMap','metalnessMap'])if(m[key])textures.add(m[key]);m.dispose();}if(this.scene.background?.isTexture)textures.add(this.scene.background);for(const tex of textures)tex.dispose();this.mixer?.stopAllAction();this.gl.dispose();}
}
