import * as T from './vendor/three.module.min.js';
import {BIG_HEAD,FLIGHT,characterAt} from './characters.js';
import {materialName} from './rig-materials.js';
const clamp=x=>Math.max(0,Math.min(1,x));
const FX={lion:'fx-lion',afuera:null,rescue:'fx-rescue',ham:'fx-ham-back',maga:'fx-speed',burger:'fx-heavy',bibi:'fx-bibi',speech:'fx-speech-wave',victim:'fx-shield',gas:null,chosen:'fx-chosen',chicken:'fx-chicken-back',bigben:'fx-bibi',presspanic:'fx-presspanic',chickenflight:null};
export class SignatureEffects{
 constructor(r){this.r=r;this.maps=new Map();this.geometry=new T.PlaneGeometry(1,1);this.fx=new T.Mesh(this.geometry,new T.MeshBasicMaterial({transparent:true,depthWrite:false,toneMapped:false,side:T.DoubleSide,opacity:0}));this.held=new T.Mesh(this.geometry,new T.MeshBasicMaterial({transparent:true,depthWrite:false,toneMapped:false,side:T.DoubleSide}));r.scene.add(this.fx,this.held);this.fx.visible=this.held.visible=false;this.v=new T.Vector3();this.dummy=new T.Object3D();this.size=1;
  this.flies=new T.InstancedMesh(new T.SphereGeometry(1,5,4),new T.MeshBasicMaterial({color:0x242428}),12);this.wings=new T.InstancedMesh(new T.SphereGeometry(1,5,4),new T.MeshBasicMaterial({color:0xc0dded,transparent:true,opacity:.65}),24);this.flies.count=this.wings.count=0;this.flies.frustumCulled=this.wings.frustumCulled=false;r.scene.add(this.flies,this.wings);
 }
 async texture(id){if(!this.maps.has(id)){const t=await new T.TextureLoader().loadAsync('../art/'+id+'.webp');t.colorSpace=T.SRGBColorSpace;this.maps.set(id,t);}return this.maps.get(id);}
 async load(index){const ids=characterAt(index).powers;await Promise.all([...new Set(ids.map(id=>FX[id]).filter(Boolean)),...ids.map(id=>'power-'+id),...(index===1?['fx-ham-front','fx-ham-back']:[])].filter(id=>!['power-lion','power-afuera','power-rescue'].includes(id)).map(id=>this.texture(id)));}
 bind(){this.headMaps=[];this.r.hero.traverse(o=>{if(!o.isMesh)return;for(const m of Array.isArray(o.material)?o.material:[o.material])if(materialName(m).startsWith('reference head '))this.headMaps.push({m,original:m.map,rear:materialName(m).endsWith('back')});});this.size=1;this.width=1;this.pelvisRest=this.r.effects.bones.pelvis?.scale.clone();}
 update(e,dt,menu){const r=this.r,id=menu?null:e.power,age=e.powerAge||0,envelope=id?Math.min(clamp(age/.35),clamp(e.powerTime/.35)):0;const target=BIG_HEAD.has(id)?1.85:id==='chicken'?.43:1;this.size+=(target-this.size)*(1-Math.exp(-dt*13));if(menu)this.size=1;const pelvis=r.effects.bones.pelvis;this.width+=((id==='burger'?1.48:1)-this.width)*(1-Math.exp(-dt*12));if(menu)this.width=1;if(pelvis&&this.pelvisRest){pelvis.scale.copy(this.pelvisRest);pelvis.scale.x*=this.width;pelvis.scale.z*=1+(this.width-1)*.45;}const head=r.effects.bones.head;if(head&&r.effects.baseHeadScale)head.scale.copy(r.effects.baseHeadScale).multiplyScalar(this.size);if(head)head.scale.x/=this.width;
  for(const h of this.headMaps){let map=h.original;if(id==='chicken')map=this.maps.get(h.rear?'fx-chicken-back':'power-chicken')||map;if(id==='ham')map=this.maps.get(h.rear?'fx-ham-back':'fx-ham-front')||map;if(h.m.map!==map){h.m.map=map;h.m.needsUpdate=true;}}
  const tex=this.maps.get(FX[id]);this.fx.visible=!!tex&&envelope>0&&!['rescue','gas','chickenflight'].includes(id);this.held.visible=false;if(this.fx.visible){if(this.fx.material.map!==tex){this.fx.material.map=tex;this.fx.material.needsUpdate=true;}this.fx.material.opacity=(id==='victim'?.55:.7)*envelope;this.fx.quaternion.copy(r.camera.quaternion);this.fx.position.copy(r.heroRoot.position).add(new T.Vector3(0,FLIGHT.has(id)?1.0:1.2,-.65));let size=FLIGHT.has(id)?2.3:age<.6?2.3:1.8;this.fx.scale.setScalar(size*(.92+Math.sin(r.clock*5)*.035));if(id==='presspanic'){const pulse=(age%.85)/.85;this.fx.scale.set(3+5*pulse,1.8+1.5*pulse,1);this.fx.material.opacity=(1-pulse)*.65*envelope;this.fx.position.z=-3;}if(id==='gas'){this.fx.position.y-=.5;this.fx.position.z-=.35;}if(id==='maga'){this.fx.position.z-=1.3;this.fx.scale.set(1.8,3.2,1);}}
  const heldId=['burger','speech','presspanic','maga'].includes(id)?id:null;if(heldId&&envelope>0){this.held.visible=true;const heldMap=this.maps.get('power-'+heldId);if(this.held.material.map!==heldMap){this.held.material.map=heldMap;this.held.material.needsUpdate=true;}this.held.material.opacity=envelope;this.held.quaternion.copy(r.camera.quaternion);if(id==='chickenflight'){r.effects.handCenter(this.held.position);this.held.position.y+=.45;this.held.scale.setScalar(1.45*(.97+Math.sin(r.clock*13)*.035));}else if(id==='maga'){head.getWorldPosition(this.held.position);this.held.position.y+=.55;this.held.scale.setScalar(.70);this.held.rotateZ((1-clamp(age/.45))*Math.PI*2);this.held.position.y+=(1-clamp(age/.45))*.8;}else{const hand=r.effects.bones.hand_L;if(hand)hand.getWorldPosition(this.held.position);else this.held.position.copy(r.heroRoot.position);this.held.position.y+=.1;this.held.scale.setScalar(id==='burger'?.6:.9);}}
  const ben=r.character?.id==='ben'&&!['GAME_OVER','NEW_HIGH_SCORE'].includes(e.state);this.flies.count=ben?8:0;this.wings.count=ben?16:0;if(ben){for(let i=0;i<8;i++){const t=r.clock*2.3+i*2.399,y=.85+Math.sin(t*1.6+i)*.32;this.v.copy(r.heroRoot.position).add(new T.Vector3(Math.cos(t)*.72,y,Math.sin(t)*.57));this.dummy.position.copy(this.v);this.dummy.rotation.set(0,t,0);this.dummy.scale.set(.016,.015,.030);this.dummy.updateMatrix();this.flies.setMatrixAt(i,this.dummy.matrix);for(let side=0;side<2;side++){this.dummy.position.copy(this.v).add(new T.Vector3((side?1:-1)*.025,.014,0));this.dummy.rotation.z=(side?1:-1)*(Math.sin(r.clock*42+i)*.5+.4);this.dummy.scale.set(.026,.005,.014);this.dummy.updateMatrix();this.wings.setMatrixAt(i*2+side,this.dummy.matrix);}}this.flies.instanceMatrix.needsUpdate=this.wings.instanceMatrix.needsUpdate=true;}
  r.heroRoot.updateMatrixWorld(true);this.stats={power:id,headScale:Number(this.size.toFixed(2)),flies:this.flies.count,flight:FLIGHT.has(id),effect:this.fx.visible};
 }
 dispose(){for(const t of this.maps.values())t.dispose();}
}
